INSERT INTO `perg` values(NULL,'	La Ãºnica letra del alfabeto espaÃ±ol que no existe en portuguÃ©s es:	','	4	');
INSERT INTO `perg` values(NULL,'	Sobre o MarquÃªs de Pombal  Ã© correto dizer que:	','	0	');
INSERT INTO `perg` values(NULL,'	A expressÃ£o laissez faire  laissez passer estÃ¡ vinculada Ã  seguinte escola econÃ´mica:	','	1	');
INSERT INTO `perg` values(NULL,'	Os sofistas desenvolveram-se em qual contexto da GrÃ©cia Antiga?	','	3	');
INSERT INTO `perg` values(NULL,'	Como ficou conhecido a noÃ§Ã£o de regime absolutista que possuÃ­a alguns princÃ­pios iluministas?	','	1	');
INSERT INTO `perg` values(NULL,'	O que o termo MesopotÃ¢mia significa?	','	2	');
INSERT INTO `perg` values(NULL,'	O ____________ compreende as reaÃ§Ãµes de sÃ­ntese de substÃ¢ncias que serÃ£o utilizadas para o crescimento do organismo e reparaÃ§Ã£o de suas perdas. A opÃ§Ã£o que substitui o espaÃ§o em branco Ã©:	','	2	');
INSERT INTO `perg` values(NULL,'	Um certo mÃ³vel se desloca com velocidade constante de 120 m/s. Esse mÃ³vel anda durante 5 percorrido pelo mÃ³vel nesse intervalo de tempo se ele nÃ£o colidir com algum obstÃ¡culo?	','	1	');
INSERT INTO `perg` values(NULL,'	A partir da DeclaraÃ§Ã£o dos Diretos do Homem e do CidadÃ£o os cidadÃ£os passaram a serem vista de que forma?	','	4	');
INSERT INTO `perg` values(NULL,'	Sobre as condiÃ§Ãµes da Terra primitiva Ã© incorreto afirma que:	','	0	');
INSERT INTO `perg` values(NULL,'	What does â€œbrideâ€ mean?	','	1	');
INSERT INTO `perg` values(NULL,'	Na final da dialÃ©tica  os movimentos anteriores formam uma:	','	2	');
INSERT INTO `perg` values(NULL,'	Identifique nome da primeira dinastia real inglesa apÃ³s a Guerra das Duas Rosas:	','	1	');
INSERT INTO `perg` values(NULL,'	Onde viveu Visconti?	','	1	');
INSERT INTO `perg` values(NULL,'	We met ________ people at the conference.	','	1	');
INSERT INTO `perg` values(NULL,'	The Simple Past of the verb of the verb â€œto doâ€ is	','	1	');
INSERT INTO `perg` values(NULL,'	O capitalismo era liderado por qual paÃ­s?	','	3	');
INSERT INTO `perg` values(NULL,'	A queratina presente na pele ajuda a evitar:	','	1	');
INSERT INTO `perg` values(NULL,'	Marca la alternativa que presenta un verbo irregular de PretÃ©rito Imperfecto de Indicativo:	','	1	');
INSERT INTO `perg` values(NULL,'	Qual dos fatores abaixo influenciou diretamente no fortalecimento do comÃ©rcio marÃ­timo britÃ¢nico?	','	2	');
INSERT INTO `perg` values(NULL,'	Um dos elementos quÃ­micos encontrados com maior frequÃªncia nos componentes nÃ£o vivos Ã©:	','	4	');
INSERT INTO `perg` values(NULL,'	Qual foi o primeiro reino a se tornar um Estado Nacional?	','	3	');
INSERT INTO `perg` values(NULL,'	Como se chamou a revista francesa responsÃ¡vel por desenvolver a Escola dos Annales?	','	0	');
INSERT INTO `perg` values(NULL,'	The expression â€œthe day before yesterdayâ€ refers to	','	3	');
INSERT INTO `perg` values(NULL,'	Alguns pÃ¡ssaros se alimentam de parasitam que vivem no pelo de rinocerontes. Qual a relaÃ§Ã£o ecolÃ³gica entre pÃ¡ssaros e parasitas?	','	2	');
INSERT INTO `perg` values(NULL,'	____ were all over the crime scene.	','	2	');
INSERT INTO `perg` values(NULL,'	Assinale a palavra que possui a vogal â€œiâ€.	','	3	');
INSERT INTO `perg` values(NULL,'	A eutrofizaÃ§Ã£o leva Ã  diminuiÃ§Ã£o da concentraÃ§Ã£o de oxigÃªnio no ambiente. Tal situaÃ§Ã£o pode ser evitada:	','	1	');
INSERT INTO `perg` values(NULL,'	Com o que a vanguarda rompeu?	','	1	');
INSERT INTO `perg` values(NULL,'	July is _____ month of the year in the U.S.	','	2	');
INSERT INTO `perg` values(NULL,'	Como sÃ£o formadas as cores secundÃ¡rias?	','	1	');
INSERT INTO `perg` values(NULL,'	Which of the adjective below means â€œcarecaâ€?	','	0	');
INSERT INTO `perg` values(NULL,'	Assinale o meio em que a linguagem e a escrita nÃ£o estÃ£o presentes:	','	4	');
INSERT INTO `perg` values(NULL,'	A forma que SÃ³crates desenvolve para conceber o discernimento Ã©:	','	0	');
INSERT INTO `perg` values(NULL,'	O monarca inglÃªs responsÃ¡vel por fortalecer a centralizaÃ§Ã£o do poder foi:	','	3	');
INSERT INTO `perg` values(NULL,'	Um microcrustÃ¡ceo que se alimenta das larvas do Aedes aegypti vem sendo utilizado no controle das populaÃ§Ãµes deste mosquito. A relaÃ§Ã£o entre esses dois organismos Ã© chamada de:	','	2	');
INSERT INTO `perg` values(NULL,'	Qual palavra abaixo possui a sÃ­laba â€“fe?	','	1	');
INSERT INTO `perg` values(NULL,'	Quando hÃ¡ um quadro de carÃªncia parcial de vitaminas dizemos que existe um quadro de:	','	2	');
INSERT INTO `perg` values(NULL,'	Qual monarca da dinastia Tudor foi responsÃ¡vel pela Reforma Anglicana na Inglaterra?	','	4	');
INSERT INTO `perg` values(NULL,'	O nome do chanceler alemÃ£o responsÃ¡vel pela unificaÃ§Ã£o territorial da Alemanha era:	','	2	');
INSERT INTO `perg` values(NULL,'	Quais desses nutrientes nÃ£o sofrem digestÃ£o e passam diretamente para a corrente sanguÃ­nea?	','	2	');
INSERT INTO `perg` values(NULL,'	He has a _____ ring.	','	2	');
INSERT INTO `perg` values(NULL,'	Playing a game of Monopoly is _____ activity they can do together.	','	0	');
INSERT INTO `perg` values(NULL,'	O que os impressionistas buscavam captar?	','	4	');
INSERT INTO `perg` values(NULL,'	Os organismos abaixo vivem em um ambiente poluÃ­do por alumÃ­nio. Qual deles apresenta maior concentraÃ§Ã£o do poluente?	','	0	');
INSERT INTO `perg` values(NULL,'	A Viagem do CapitÃ£o Tornado Ã© um(a)	','	2	');
INSERT INTO `perg` values(NULL,'	Um exemplo de movimento de crise filosÃ³fica no Brasil foi:	','	0	');
INSERT INTO `perg` values(NULL,'	O ressurgimento do comÃ©rcio e das cidades foi uma consequÃªncia do seguinte episÃ³dio:	','	0	');
INSERT INTO `perg` values(NULL,'	Although means	','	1	');
INSERT INTO `perg` values(NULL,'	IÂ had lunch ____ a beautiful beach.	','	3	');
INSERT INTO `perg` values(NULL,'	Deixar a aporia de lado significa:	','	0	');
INSERT INTO `perg` values(NULL,'	In which of the options the use of possessive pronouns is correct?	','	2	');
INSERT INTO `perg` values(NULL,'	O que encontramos representado na arte muralista?	','	0	');
INSERT INTO `perg` values(NULL,'	Em que continente se localiza o territÃ³rio da civilizaÃ§Ã£o egÃ­pcia?	','	4	');
INSERT INTO `perg` values(NULL,'	SÃ£o relaÃ§Ãµes ecolÃ³gicas desarmÃ´nicas:	','	1	');
INSERT INTO `perg` values(NULL,'	The comparative of superiority form of the adjective â€œhappyâ€ is	','	1	');
INSERT INTO `perg` values(NULL,'	No _____________ as temperaturas sÃ£o mais quentes e no ____________ mais frias.	','	3	');
INSERT INTO `perg` values(NULL,'	Os objetos indÃ­genas que hoje sÃ£o considerados arte foram produzidos com fins	','	2	');
INSERT INTO `perg` values(NULL,'	Marca la alternativa que presenta un artÃ­culo determinado:	','	1	');
INSERT INTO `perg` values(NULL,'	Assinale a alternativa que apresenta corretamente o conceito de territÃ³rio:	','	1	');
INSERT INTO `perg` values(NULL,'	Alimentos perecÃ­veis sÃ£o aqueles:	','	2	');
INSERT INTO `perg` values(NULL,'	Gustave Courbet e HonorÃ© Daumier foram	','	2	');
INSERT INTO `perg` values(NULL,'	A Marcha da FamÃ­lia com Deus pela Liberdade buscou estabelecer com o Estado uma relaÃ§Ã£o de:	','	0	');
INSERT INTO `perg` values(NULL,'	Qual das palavras abaixo nÃ£o possui sÃ­labas da letra â€“n?	','	4	');
INSERT INTO `perg` values(NULL,'	She is _____ Tom.	','	3	');
INSERT INTO `perg` values(NULL,'	Marca la alternativa que presenta un verbo en indicativo:	','	2	');
INSERT INTO `perg` values(NULL,'	Na palavra amizade existem quantas consoantes?	','	2	');
INSERT INTO `perg` values(NULL,'	Onde estÃ¡ localizada a caverna de Lascaux?	','	2	');
INSERT INTO `perg` values(NULL,'	Marca la opciÃ³n que sÃ³lo contiene adverbios de tiempo.	','	3	');
INSERT INTO `perg` values(NULL,'	Qual das alternativas indica um dos maiores nomes da filosofia na contemporaneidade?	','	3	');
INSERT INTO `perg` values(NULL,'	Gustave Flaubert representa o Realismo em qual linguagem artÃ­stica?	','	2	');
INSERT INTO `perg` values(NULL,'	Dos seres abaixo o Ãºnico que possui clorofila Ã©:	','	4	');
INSERT INTO `perg` values(NULL,'	Qual era o elemento mais abordado por Degas em suas pinturas?	','	2	');
INSERT INTO `perg` values(NULL,'	O filÃ³sofo anarquista membro do Parlamento francÃªs e que nÃ£o identificava a greve como um instrumento de pressÃ£o vÃ¡lido foi:	','	2	');
INSERT INTO `perg` values(NULL,'	Os seres eucariontes sÃ£o aqueles que:	','	0	');
INSERT INTO `perg` values(NULL,'	Na classificaÃ§Ã£o de Lineu apÃ³s o filo vem:	','	0	');
INSERT INTO `perg` values(NULL,'	El verbo â€œdeberâ€ conjugado en la primera persona del plural en presente de subjuntivo es:	','	1	');
INSERT INTO `perg` values(NULL,'	Sabemos que o positivismo foi uma teoria de desenvolvimento social muito importante para o inÃ­cio da RepÃºblica brasileira. Esta teoria foi desenvolvida por:	','	0	');
INSERT INTO `perg` values(NULL,'	Os artistas da MissÃ£o Francesa	','	0	');
INSERT INTO `perg` values(NULL,'	Sandy is 70 centimeters tall. Sara is 120 centimeters tall. Donna is 90 centimeters tall. Sandy is _____.	','	3	');
INSERT INTO `perg` values(NULL,'	A principal crÃ­tica de SÃ³crates aos sofistas era direcionada:	','	1	');
INSERT INTO `perg` values(NULL,'	As obras de arte prÃ©-histÃ³ricas foram produzidas por	','	1	');
INSERT INTO `perg` values(NULL,'	Que importantes pensadores alemÃ£es criaram e desenvolveram o moderno conceito de materialismo histÃ³rico?	','	1	');
INSERT INTO `perg` values(NULL,'	Donâ€™t use ____ perfume!	','	1	');
INSERT INTO `perg` values(NULL,'	Sobre a DeclaraÃ§Ã£o de IndulgÃªncias Ã© correto afirmar que:	','	0	');
INSERT INTO `perg` values(NULL,'	Marque a letra M bastÃ£o minÃºscula.	','	1	');
INSERT INTO `perg` values(NULL,'	He is trying to be _____ than Robert.	','	0	');
INSERT INTO `perg` values(NULL,'	AtravÃ©s do Tratado de Portsmouth:	','	2	');
INSERT INTO `perg` values(NULL,'	Quem trouxe o teatro para o Brasil?	','	2	');
INSERT INTO `perg` values(NULL,'	Qual conceito que nÃ£o foi trabalhado por Durkheim na obra Da divisÃ£o do trabalho social?	','	3	');
INSERT INTO `perg` values(NULL,'	O territÃ³rio da SumÃ©ria foi conquistado por qual povo?	','	4	');
INSERT INTO `perg` values(NULL,'	NÃ£o se apresenta como uma boa fonte de micronutrientes:	','	3	');
INSERT INTO `perg` values(NULL,'	A primeira fase da Primeira Guerra Mundial ficou conhecida como:	','	2	');
INSERT INTO `perg` values(NULL,'	Sara`s hair is ______ Sylviaâ€™s.	','	1	');
INSERT INTO `perg` values(NULL,'	They stayed in a _____.	','	1	');
INSERT INTO `perg` values(NULL,'	O muralismo mexicano foi influenciado pelo quÃª?	','	0	');
INSERT INTO `perg` values(NULL,'	A palavra cultura significa o quÃª?	','	1	');
INSERT INTO `perg` values(NULL,'	Qual a importÃ¢ncia do cÃ¡lcio para o organismo?	','	4	');
INSERT INTO `perg` values(NULL,'	O desenvolvimento da ciÃªncia e da tecnologia possibilitou que	','	0	');
INSERT INTO `perg` values(NULL,'	O modo de produÃ§Ã£o caracterizado pelas relaÃ§Ãµes assalariadas de produÃ§Ã£o Ã© o:	','	1	');
INSERT INTO `perg` values(NULL,'	O estruturalismo analisa o mito a partir:	','	4	');
INSERT INTO `perg` values(NULL,'	O Antropocentrismo Ã© uma caracterÃ­stica importante do Renascimento. Identifique o que essa caracterÃ­stica significa:	','	0	');
INSERT INTO `perg` values(NULL,'	Jean-Baptiste Poquelin era conhecido tambÃ©m como	','	4	');
INSERT INTO `perg` values(NULL,'	As contradiÃ§Ãµes de uma sociedade moderna podem levar a danos colaterais. Esses danos foi chamado por Durkheim de:	','	0	');
INSERT INTO `perg` values(NULL,'	O grupo de tenentes e capitÃ£es do ExÃ©rcito liderados por LuÃ­s Carlos Prestes ficou conhecido como:	','	2	');
INSERT INTO `perg` values(NULL,'	â€œShipâ€ means	','	0	');
INSERT INTO `perg` values(NULL,'	As vitaminas K e B12 podem ser sintetizadas em que regiÃ£o do sistema digestÃ³rio?	','	3	');
INSERT INTO `perg` values(NULL,'	Identifique o presidente brasileiro que ficou conhecido como "marechal de ferro":	','	2	');
INSERT INTO `perg` values(NULL,'	A filosofia de Hegel sofreu duras crÃ­ticas. Um de seus maiores contestadores foi:	','	2	');
INSERT INTO `perg` values(NULL,'	The Nile is _____ river in the world.	','	1	');
INSERT INTO `perg` values(NULL,'	A trajetÃ³ria da Terra e de outras planetas ao redor do Sol Ã© o movimento conhecido como:	','	0	');
INSERT INTO `perg` values(NULL,'	La forma verbal â€œsalesâ€ estÃ¡ conjugada en el mismo tiempo y persona que:	','	1	');
INSERT INTO `perg` values(NULL,'	SÃ£o consideradas dentro do campo das CiÃªncias Sociais as disciplinas:	','	2	');
INSERT INTO `perg` values(NULL,'	Os socialistas utÃ³picos sÃ£o classificados dessa maneira por:	','	0	');
INSERT INTO `perg` values(NULL,'	Auguste Comte identificou o progresso das sociedades atravÃ©s da:	','	4	');
INSERT INTO `perg` values(NULL,'	La estructura compuesta por â€œestar + adjetivoâ€ sirve para indicar:	','	4	');
INSERT INTO `perg` values(NULL,'	Os seres humanos sÃ£o:	','	2	');
INSERT INTO `perg` values(NULL,'	â€œ____ do you to school?â€ â€œBy foot.â€	','	3	');
INSERT INTO `perg` values(NULL,'	â€œ____ time do they get up?â€ â€œAt 8 oâ€™clock.â€	','	2	');
INSERT INTO `perg` values(NULL,'	Os impressionistas rejeitavam a tÃ©cnica do(a)	','	2	');
INSERT INTO `perg` values(NULL,'	O Ãºnico organismo que nÃ£o Ã© pluricelular presente abaixo Ã©:	','	0	');
INSERT INTO `perg` values(NULL,'	Qual elemento era produzido na cultura africana com funÃ§Ã£o ritual?	','	1	');
INSERT INTO `perg` values(NULL,'	A teoria polÃ­tica de Karl Marx fundamenta-se no:	','	1	');
INSERT INTO `perg` values(NULL,'	What does it mean â€œchildrenâ€?	','	3	');
INSERT INTO `perg` values(NULL,'	A letra bastÃ£o maiÃºscula Ã© _______ que a letra bastÃ£o minÃºscula.	','	2	');
INSERT INTO `perg` values(NULL,'	No fim do sÃ©culo XIX e comeÃ§o do sÃ©culo XX a relaÃ§Ã£o entre mitos e filosofia era vista como:	','	2	');
INSERT INTO `perg` values(NULL,'	Quem foi Claude Monet?	','	1	');
INSERT INTO `perg` values(NULL,'	A revolta comandada por um marinheiro negro contra os castigos fÃ­sicos nas forÃ§as armadas foi:	','	1	');
INSERT INTO `perg` values(NULL,'	The feminine of â€œmeio-irmÃ£oâ€ is	','	2	');
INSERT INTO `perg` values(NULL,'	Classes start _____ February.	','	3	');
INSERT INTO `perg` values(NULL,'	Podemos afirmar que Pathera onca e Panthera leo possuem:	','	1	');
INSERT INTO `perg` values(NULL,'	Qual o tempo que a Terra leva para completar o seu movimento ao redor do Sol?	','	1	');
INSERT INTO `perg` values(NULL,'	A teoria da evoluÃ§Ã£o das espÃ©cies afirma que os animais e os seres humanos sofreram na seleÃ§Ã£o natural:	','	0	');
INSERT INTO `perg` values(NULL,'	The comparative of superiority form of the adjective â€œhotâ€ is	','	2	');
INSERT INTO `perg` values(NULL,'	SÃ³crates Ã© um dos principais nomes da filosofia porque:	','	2	');
INSERT INTO `perg` values(NULL,'	SÃ£o fontes de carboidratos:	','	3	');
INSERT INTO `perg` values(NULL,'	Identifique a revoluÃ§Ã£o que eclodiu durante a Primeira Guerra Mundial:	','	1	');
INSERT INTO `perg` values(NULL,'	Qual elemento do iluminismo teve forte influÃªncia sobre o surgimento da sociologia?	','	3	');
INSERT INTO `perg` values(NULL,'	O Cartismo foi um movimento polÃ­tico que ocorreu durante o seguinte perÃ­odo:	','	1	');
INSERT INTO `perg` values(NULL,'	A interpretaÃ§Ã£o sobre o que Ã© arte varia de acordo com	','	1	');
INSERT INTO `perg` values(NULL,'	A energia se origina no nÃ­vel trÃ³fico:	','	2	');
INSERT INTO `perg` values(NULL,'	A lombriga e o ser humano vivem uma relaÃ§Ã£o ecolÃ³gica classificada como:	','	0	');
INSERT INTO `perg` values(NULL,'	A etapa que inicia a discussÃ£o do processo dialÃ©tico para SÃ³crates Ã©:	','	3	');
INSERT INTO `perg` values(NULL,'	Em que estrutura do tubo digestÃ³rio ocorre a produÃ§Ã£o do bolo fecal.	','	2	');
INSERT INTO `perg` values(NULL,'	This museum is _____ the first one.	','	3	');
INSERT INTO `perg` values(NULL,'	This is Emilyâ€™s room. It is ____ room.	','	3	');
INSERT INTO `perg` values(NULL,'	A partir de qual ano o voto foi garantido de forma plena a todas as mulheres no Brasil?	','	4	');
INSERT INTO `perg` values(NULL,'	Quando se inicia o inverno no HemisfÃ©rio Norte?	','	2	');
INSERT INTO `perg` values(NULL,'	O Futurismo valorizava	','	3	');
INSERT INTO `perg` values(NULL,'	Uma molÃ©cula formada por mais de dez peptÃ­deos Ã© chamada de:	','	0	');
INSERT INTO `perg` values(NULL,'	Assinale a palavra que nÃ£o Ã© formada por uma sÃ­laba com a letra b.	','	3	');
INSERT INTO `perg` values(NULL,'	The ____ are late.	','	2	');
INSERT INTO `perg` values(NULL,'	Um zigoto possui:	','	3	');
INSERT INTO `perg` values(NULL,'	Lisa broke ____ leg.	','	3	');
INSERT INTO `perg` values(NULL,'	A grande preocupaÃ§Ã£o dos prÃ©-socrÃ¡ticos Ã© em encontrar a (o):	','	2	');
INSERT INTO `perg` values(NULL,'	A BalanÃ§a Comercial FavorÃ¡vel e o Metalismo eram caracterÃ­sticas do:	','	3	');
INSERT INTO `perg` values(NULL,'	Assinale a alternativa em que a palavra nÃ£o Ã© formada por sÃ­laba com a letra c.	','	4	');
INSERT INTO `perg` values(NULL,'	Quem pintou a obra O nascimento da VÃªnus?	','	1	');
INSERT INTO `perg` values(NULL,'	PedaÃ§os de rocha vagando pelo espaÃ§o sÃ£o conhecidos como:	','	1	');
INSERT INTO `perg` values(NULL,'	Tennis is _____ football.	','	1	');
INSERT INTO `perg` values(NULL,'	Qual elemento nÃ£o era uma base da sociologia de Auguste Comte?	','	3	');
INSERT INTO `perg` values(NULL,'	A reduÃ§Ã£o do efetivo militar alemÃ£o para 100 mil homens e proibiÃ§Ã£o do uso de artilharia pesada foi imposta pelo seguinte tratado:	','	0	');
INSERT INTO `perg` values(NULL,'	Os vestÃ­gios que permitem ao historiador reconstruir e recontar uma histÃ³ria sÃ£o:	','	2	');
INSERT INTO `perg` values(NULL,'	A fase final do movimento dialÃ©tico real Ã©:	','	0	');
INSERT INTO `perg` values(NULL,'	Qual a idade aproximada do Universo?	','	1	');
INSERT INTO `perg` values(NULL,'	Qual era uma das caracterÃ­sticas dos artistas do Realismo?	','	3	');
INSERT INTO `perg` values(NULL,'	Ethan is ______ boy that I know.	','	4	');
INSERT INTO `perg` values(NULL,'	December is _____ month of the year in my country.	','	0	');
INSERT INTO `perg` values(NULL,'	I go _____ school every day.	','	0	');
INSERT INTO `perg` values(NULL,'	NÃ£o pode ser considerado um direito civil:	','	4	');
INSERT INTO `perg` values(NULL,'	Assinale a alternativa que indica corretamente o conceito de fronteira efetiva:	','	1	');
INSERT INTO `perg` values(NULL,'	Marca la alternativa que presenta un artÃ­culo indeterminado:	','	4	');
INSERT INTO `perg` values(NULL,'	Qual Ã© uma caracterÃ­stica das catedrais gÃ³ticas?	','	1	');
INSERT INTO `perg` values(NULL,'	Quando Rugendas veio para o Brasil?	','	3	');
INSERT INTO `perg` values(NULL,'	NÃ£o pode ser considerada uma pauta do movimento feminista:	','	0	');
INSERT INTO `perg` values(NULL,'	Na palavra ABACATES qual Ã© a letra que se repete?	','	3	');
INSERT INTO `perg` values(NULL,'	CÃ³mo se dice â€œterÃ§a-feiraâ€ en espaÃ±ol:	','	2	');
INSERT INTO `perg` values(NULL,'	Quais os trÃªs poderes defendidos por Montesquieu?	','	4	');
INSERT INTO `perg` values(NULL,'	SubstÃ¢ncias quÃ­micas provenientes dos alimentos e que sÃ£o essenciais Ã  sobrevivÃªncia humana sÃ£o chamados de:	','	0	');
INSERT INTO `perg` values(NULL,'	Qual tipo de democracia teve sua origem marcada pelas RevoluÃ§Ãµes Burguesas que ocorreram na Europa entre os sÃ©culos XVII e XIX?	','	4	');
INSERT INTO `perg` values(NULL,'	Qual o nome do sistema polÃ­tico atravÃ©s do qual o rei concentra todos os poderes em suas mÃ£os?	','	1	');
INSERT INTO `perg` values(NULL,'	O afresco A Ãºltima ceia foi feito por quem?	','	2	');
INSERT INTO `perg` values(NULL,'	O debate sobre a organizaÃ§Ã£o do espaÃ§o feito pela Geografia Ã© auxiliado por uma categoria que estÃ¡ ligada Ã  ideia de domÃ­nio ou gestÃ£o de determinada Ã¡rea. Estas caracterÃ­sticas correspondem Ã  categoria:	','	4	');
INSERT INTO `perg` values(NULL,'	Marque a opÃ§Ã£o que representa uma relaÃ§Ã£o ecolÃ³gica intraespecÃ­fica e harmÃ´nica.	','	4	');
INSERT INTO `perg` values(NULL,'	â€œ____ are you wearing?â€ â€œWhite t-shirt and jeans.â€	','	4	');
INSERT INTO `perg` values(NULL,'	Sinalize a opÃ§Ã£o em que Ã© apresentada uma relaÃ§Ã£o ecolÃ³gica interespecÃ­fica harmÃ´nica.	','	0	');
INSERT INTO `perg` values(NULL,'	Which of the options below is not a farewell?	','	2	');
INSERT INTO `perg` values(NULL,'	Uma das consequÃªncias da crise econÃ´mica alemÃ£ do perÃ­odo entre guerras foi:	','	1	');
INSERT INTO `perg` values(NULL,'	A PredestinaÃ§Ã£o foi uma doutrina desenvolvida por qual reformador?	','	3	');
INSERT INTO `perg` values(NULL,'	O escorbuto Ã© causado pela falta no organismo da vitamina:	','	2	');
INSERT INTO `perg` values(NULL,'	A crÃ­tica profunda em relaÃ§Ã£o ao sistema republicano estava presente no seguinte movimento social:	','	2	');
INSERT INTO `perg` values(NULL,'	O que Ã© possÃ­vel encontrar no cÃ­rculo cromÃ¡tico?	','	0	');
INSERT INTO `perg` values(NULL,'	Como caracteriza-se a consciÃªncia coletiva na solidariedade orgÃ¢nica?	','	4	');
INSERT INTO `perg` values(NULL,'	O valor de 45Âº Celsius equivale a quanto na escala Fahrenheit?	','	0	');
INSERT INTO `perg` values(NULL,'	SÃ£o considerados micronutrientes:	','	1	');
INSERT INTO `perg` values(NULL,'	A filosofia de Comte pode ser sintetizada na formulaÃ§Ã£o da seguinte lei:	','	2	');
INSERT INTO `perg` values(NULL,'	A grande preocupaÃ§Ã£o de Karl Marx estÃ¡ em analisar qual modo de produÃ§Ã£o?	','	4	');
INSERT INTO `perg` values(NULL,'	_______ car.	','	2	');
INSERT INTO `perg` values(NULL,'	O termo sofista significa:	','	1	');
INSERT INTO `perg` values(NULL,'	Quando foi inaugurada a Torre Eiffel?	','	3	');
INSERT INTO `perg` values(NULL,'	â€œ_____ shoes are these?â€ â€œTheyâ€™re mine.â€	','	3	');
INSERT INTO `perg` values(NULL,'	Em que cidade D. Pedro II mandou construir uma catedral com referÃªncias gÃ³ticas?	','	2	');
INSERT INTO `perg` values(NULL,'	Direito que passou a prezar pela participaÃ§Ã£o da populaÃ§Ã£o nas diversas relaÃ§Ãµes de poder:	','	0	');
INSERT INTO `perg` values(NULL,'	Marque a letra f bastÃ£o maiÃºscula.	','	0	');
INSERT INTO `perg` values(NULL,'	Identifique o movimento intelectual difundido durante a RenascenÃ§a que inspirou o movimento iluminista:	','	2	');
INSERT INTO `perg` values(NULL,'	A Ãºnica frase em que ocorre a intertextualidade Ã©:	','	1	');
INSERT INTO `perg` values(NULL,'	Identifique a revolta que teve como objetivo acabar com o costume de castigar fisicamente os marinheiros:	','	2	');
INSERT INTO `perg` values(NULL,'	Qual das alternativas expressa a ideia de TrajetÃ³ria?	','	1	');
INSERT INTO `perg` values(NULL,'	Marca la alternativa que presenta una perÃ­frasis verbal que indica futuro inmediato:	','	2	');
INSERT INTO `perg` values(NULL,'	As cÃ©lulas que compÃµe o corpo dos seres vivos sÃ£o chamadas de:	','	4	');
INSERT INTO `perg` values(NULL,'	A geraÃ§Ã£o espontÃ¢nea tambÃ©m pode ser chamada de:	','	2	');
INSERT INTO `perg` values(NULL,'	Planeta conhecido como Estrela Dalva:	','	1	');
INSERT INTO `perg` values(NULL,'	Uma das caracterÃ­sticas da RevoluÃ§Ã£o TecnocÃ­entifica Ã©:	','	4	');
INSERT INTO `perg` values(NULL,'	O eclipse parcial do Sol Ã© observado nas regiÃµes da Terra situadas na __________ da Lua.	','	2	');
INSERT INTO `perg` values(NULL,'	A funÃ§Ã£o exercida pela quitina e pela celulose Ã©:	','	2	');
INSERT INTO `perg` values(NULL,'	A noÃ§Ã£o de que a Terra estÃ¡ no centro do universo Ã© conhecida como:	','	1	');
INSERT INTO `perg` values(NULL,'	O nome do imperador da Alemanha na Ã©poca da Primeira Guerra era:	','	3	');
INSERT INTO `perg` values(NULL,'	Identifique a alternativa que contÃ©m um dos pontos defendidos pelos iluministas:	','	2	');
INSERT INTO `perg` values(NULL,'	Is that for _____?	','	3	');
INSERT INTO `perg` values(NULL,'	___________________________ sÃ£o formados um aÃ§Ãºcar ou um par deles e sÃ£o de fÃ¡cil assimilaÃ§Ã£o.	','	3	');
INSERT INTO `perg` values(NULL,'	Qual tipo de coesÃ£o social caracteriza-se por haver uma maior especializaÃ§Ã£o das funÃ§Ãµes?	','	4	');
INSERT INTO `perg` values(NULL,'	Assinale a alternativa que indica corretamente o geÃ³grafo responsÃ¡vel por desenvolver o conceito de topofilia.	','	2	');
INSERT INTO `perg` values(NULL,'	Ann is _____ girl Iâ€™ve ever seen.	','	1	');
INSERT INTO `perg` values(NULL,'	Identifique o Ãºnico acontecimento que de alguma maneira influenciou na eclosÃ£o da Primeira Guerra Mundial:	','	1	');
INSERT INTO `perg` values(NULL,'	Your bag is _____ mine.	','	4	');
INSERT INTO `perg` values(NULL,'	Assinale a alternativa que indica o ano que ocorreu a queda do Muro de Berlim:	','	1	');
INSERT INTO `perg` values(NULL,'	A Commedia dellâ€™Arte Ã© uma manifestaÃ§Ã£o	','	3	');
INSERT INTO `perg` values(NULL,'	A alegoria da caverna foi formulada por:	','	1	');
INSERT INTO `perg` values(NULL,'	Identifique o nome da Ãºltima dinastia a ocupar o trono russo:	','	3	');
INSERT INTO `perg` values(NULL,'	The tsunami of 2004 was _____ disaster in history.	','	0	');
INSERT INTO `perg` values(NULL,'	A corrente pluralista teve como seu principal nome:	','	3	');
INSERT INTO `perg` values(NULL,'	A busca por reviver a cultura greco-romana clÃ¡ssica era uma caracterÃ­stica do:	','	3	');
INSERT INTO `perg` values(NULL,'	A obesidade pode desencadear quadros de:	','	1	');
INSERT INTO `perg` values(NULL,'	Which of the options below means â€œna esquinaâ€?	','	2	');
INSERT INTO `perg` values(NULL,'	Jean-Baptiste Debret veio para o Brasil com	','	1	');
INSERT INTO `perg` values(NULL,'	Stonehenge Ã© uma	','	2	');
INSERT INTO `perg` values(NULL,'	Julie closed the _____.	','	3	');
INSERT INTO `perg` values(NULL,'	Elige la palabra que tenga la colocaciÃ³n del artÃ­culo de forma incorrecta:	','	2	');
INSERT INTO `perg` values(NULL,'	A Revolta da Vacina ocorreu na seguinte cidade:	','	3	');
INSERT INTO `perg` values(NULL,'	Locke defendeu que tipo de democracia?	','	0	');
INSERT INTO `perg` values(NULL,'	My sisterâ€™s husband is my	','	3	');
INSERT INTO `perg` values(NULL,'	Mammoths _____ grass.	','	3	');
INSERT INTO `perg` values(NULL,'	Acontecimento histÃ³rico que foi de extrema importÃ¢ncia para a consagraÃ§Ã£o dos direitos civis:	','	0	');
INSERT INTO `perg` values(NULL,'	A fase dialÃ©tica do ser em si Ã© a:	','	0	');
INSERT INTO `perg` values(NULL,'	Planeta gasoso com nÃºcleo rochoso e atmosfera contendo amÃ´nia:	','	1	');
INSERT INTO `perg` values(NULL,'	A maiÃªutica faz referÃªncia:	','	0	');
INSERT INTO `perg` values(NULL,'	J. Borges Ã© um artista que trabalha com qual tÃ©cnica?	','	2	');
INSERT INTO `perg` values(NULL,'	Como ficou conhecida a reaÃ§Ã£o da Igreja CatÃ³lica Ã  Reforma Protestante?	','	3	');
INSERT INTO `perg` values(NULL,'	A grande preocupaÃ§Ã£o da escola jÃ´nica era:	','	1	');
INSERT INTO `perg` values(NULL,'	Qual desses Ã© o delito que SÃ³crates foi acusado e culminou na sua morte?	','	1	');
INSERT INTO `perg` values(NULL,'	Acredita-se que Stonehenge tenha sido criado como um	','	1	');
INSERT INTO `perg` values(NULL,'	Foi a mulher responsÃ¡vel por fundar a primeira escola para meninas no Brasil:	','	3	');
INSERT INTO `perg` values(NULL,'	Galileu Galilei foi um cientista muito perseguido em sua Ã©poca por defender que o centro do Sistema Solar era o Sol e nÃ£o a Terra. Idea que vai de encontro com a Teoria:	','	0	');
INSERT INTO `perg` values(NULL,'	What is the masculine of â€œgirlfriendâ€?	','	4	');
INSERT INTO `perg` values(NULL,'	O cientista conhecido por propor que vermes surgiam a partir de ovos colocados por moscas Ã© o:	','	0	');
INSERT INTO `perg` values(NULL,'	El verbo â€œpoderâ€ conjugado en la tercera persona del plural en PretÃ©rito Imperfecto de Subjuntivo:	','	2	');
INSERT INTO `perg` values(NULL,'	A Escola Positivista tambÃ©m Ã© conhecida como:	','	2	');
INSERT INTO `perg` values(NULL,'	O principal nome do idealismo alemÃ£o foi:	','	4	');
INSERT INTO `perg` values(NULL,'	A demarcaÃ§Ã£o de terras de comunidades quilombolas Ã© uma luta do movimento negro. Um dos principais objetivos dessa polÃ­tica pÃºblica Ã© viabilizar a promoÃ§Ã£o de:	','	1	');
INSERT INTO `perg` values(NULL,'	Em qual livro Durkheim trabalha o conceito de coesÃ£o social?	','	4	');
INSERT INTO `perg` values(NULL,'	Qual lema abaixo tem sua origem na concepÃ§Ã£o positivista?	','	2	');
INSERT INTO `perg` values(NULL,'	O objeto de estudo construÃ­do por Durkheim pode ser considerado:	','	0	');
INSERT INTO `perg` values(NULL,'	I was born _____ May.	','	0	');
INSERT INTO `perg` values(NULL,'	Ã‰ possÃ­vel afirmar que o objetivo da HistÃ³ria Ã©:	','	0	');
INSERT INTO `perg` values(NULL,'	Uma importante caracterÃ­stica da cultura religiosa egÃ­pcia Ã© que o faraÃ³ possuÃ­a um carÃ¡ter divino que:	','	1	');
INSERT INTO `perg` values(NULL,'	O movimento LGBT luta pela defesa do direito de:	','	4	');
INSERT INTO `perg` values(NULL,'	Qual forma de governo era almejada pelas revoltas emancipacionistas?	','	2	');
INSERT INTO `perg` values(NULL,'	SÃ£o os direitos visam garantir uma vida digna atravÃ©s do mÃ­nimo de bem-estar econÃ´mico instituÃ­do por cada sociedade:	','	3	');
INSERT INTO `perg` values(NULL,'	O nome MesopotÃ¢mia diz muito sobre o seu territÃ³rio. O que este nome significa?	','	2	');
INSERT INTO `perg` values(NULL,'	O uso da razÃ£o foi elemento fundamental de qual evento histÃ³rico ligado ao surgimento da sociologia?	','	3	');
INSERT INTO `perg` values(NULL,'	Identifique a alternativa que corresponde a um movimento messiÃ¢nico ocorrido na Primeira RepÃºblica:	','	3	');
INSERT INTO `perg` values(NULL,'	O ___________ estÃ¡ Ã© determinado pelos genes que recebeu de seus pais mais a interaÃ§Ã£o com o ambiente. Marque a alternativa correta:	','	1	');
INSERT INTO `perg` values(NULL,'	Carlos Ptolomeu sintetizou uma teoria para explicar a ordenaÃ§Ã£o do Sistema Solar conhecida como:	','	3	');
INSERT INTO `perg` values(NULL,'	Qual Ã© o nome do rio que foi a base do desenvolvimento social e econÃ´mico no Egito?	','	2	');
INSERT INTO `perg` values(NULL,'	Sobre a relaÃ§Ã£o mitos e escrita Ã© correto afirmar:	','	0	');
INSERT INTO `perg` values(NULL,'	Qual conhecimento compreende um esforÃ§o para dar sentido racional aos mistÃ©rios do mundo com base no questionamento e na reflexÃ£o?	','	2	');
INSERT INTO `perg` values(NULL,'	Em qual das camadas da pele Ã© possÃ­vel encontrar energia estocada em forma de gordura?	','	2	');
INSERT INTO `perg` values(NULL,'	Sobre o National Covenant Ã© correto afirmar que:	','	2	');
INSERT INTO `perg` values(NULL,'	O conjunto de toda as reaÃ§Ãµes bioquÃ­micas que ocorrem no corpo Ã© chamado de:	','	1	');
INSERT INTO `perg` values(NULL,'	James is _____ boy on the team.	','	3	');
INSERT INTO `perg` values(NULL,'	A salvaÃ§Ã£o pela fÃ© foi uma afirmaÃ§Ã£o de:	','	2	');
INSERT INTO `perg` values(NULL,'	Sabemos que a Primeira Guerra Mundial durou cerca de quatro anos. Identifique o ano em que o conflito foi encerrado:	','	1	');
INSERT INTO `perg` values(NULL,'	Em qual paÃ­s fica a caverna de Altamira?	','	0	');
INSERT INTO `perg` values(NULL,'	Identifique a espÃ©cie que deu inÃ­cio Ã  domesticaÃ§Ã£o de animais e promoveu a RevoluÃ§Ã£o AgrÃ­cola:	','	3	');
INSERT INTO `perg` values(NULL,'	A _________________ Ã© a camada mais externa da pele.	','	1	');
INSERT INTO `perg` values(NULL,'	Quais sÃ£o os principais pensadores da escola EleÃ¡tica?	','	3	');
INSERT INTO `perg` values(NULL,'	Which of the object pronouns below refers to the second person plural?	','	3	');
INSERT INTO `perg` values(NULL,'	Identifique quem sucedeu a Carlos II apÃ³s a sua morte:	','	1	');
INSERT INTO `perg` values(NULL,'	â€œThereforeâ€ means	','	2	');
INSERT INTO `perg` values(NULL,'	Winter is ______ season of the year in Europe.	','	2	');
INSERT INTO `perg` values(NULL,'	Na classificaÃ§Ã£o de Lineu antes da ordem vem:	','	0	');
INSERT INTO `perg` values(NULL,'	Ã€s margens de qual rio se desenvolveu a antiga civilizaÃ§Ã£o egÃ­pcia?	','	4	');
INSERT INTO `perg` values(NULL,'	Assinale a alternativa que indica corretamente o conceito de agricultura orgÃ¢nica:	','	4	');
INSERT INTO `perg` values(NULL,'	O surgimento da filosofia Ã© marcado pelo uso da:	','	3	');
INSERT INTO `perg` values(NULL,'	Em que paÃ­s teve inÃ­cio o processo de industrializaÃ§Ã£o?	','	2	');
INSERT INTO `perg` values(NULL,'	Uma dieta equilibrada nÃ£o deve conter:	','	4	');
INSERT INTO `perg` values(NULL,'	Non-smokers usually live ______ smokers.	','	1	');
INSERT INTO `perg` values(NULL,'	Uma importante caracterÃ­stica da cultura religiosa egÃ­pcia Ã© que o faraÃ³ possuÃ­a um carÃ¡ter divino que:	','	1	');
INSERT INTO `perg` values(NULL,'	Sara sits ____ me.	','	4	');
INSERT INTO `perg` values(NULL,'	A _____________ Ã© encontrada no estÃ´mago e ativada justamente pelo ambiente de acidez encontrado no Ã³rgÃ£o.	','	0	');
INSERT INTO `perg` values(NULL,'	Identifique a seguir um autor apoiador do Absolutismo:	','	3	');
INSERT INTO `perg` values(NULL,'	A bile Ã© armazenada:	','	3	');
INSERT INTO `perg` values(NULL,'	She goes _____ the ballet classes every week.	','	4	');
INSERT INTO `perg` values(NULL,'	(VUNESP). Uma das relaÃ§Ãµes colorÃ­sticas Ã© a relativa Ã s â€œtemperaturasâ€ cromÃ¡ticas. Sua origem remonta Ã s experiÃªncias humanas imemoriais. SÃ£o consideradas cores quentes primÃ¡rias:	','	0	');
INSERT INTO `perg` values(NULL,'	â€œMust notâ€ is used to indicate	','	4	');
INSERT INTO `perg` values(NULL,'	Qual o menor planeta do nosso Sistema Solar?	','	1	');
INSERT INTO `perg` values(NULL,'	Uma das consequÃªncias diretas da RevoluÃ§Ã£o industrial foi:	','	0	');
INSERT INTO `perg` values(NULL,'	El infinitivo de â€œconsigoâ€ tiene la misma terminaciÃ³n que:	','	4	');
INSERT INTO `perg` values(NULL,'	A eutrofizaÃ§Ã£o Ã© um processo que pode ser natural ou causado por aÃ§Ã£o antrÃ³pica. O homem contribui para a eutrofizaÃ§Ã£o dos corpos hÃ­dricos quando:	','	1	');
INSERT INTO `perg` values(NULL,'	Rui Barbosa foi ministro da Fazenda no governo de:	','	4	');
INSERT INTO `perg` values(NULL,'	Os direitos de meio ambiente podem ser classificados como:	','	2	');
INSERT INTO `perg` values(NULL,'	Assinale a alternativa que indica um monossacarÃ­deo.	','	3	');
INSERT INTO `perg` values(NULL,'	La palabra â€œDETRÃSâ€ se clasifica como:	','	3	');
INSERT INTO `perg` values(NULL,'	O que as palavras sÃ£o capazes de nos transmitir?	','	2	');
INSERT INTO `perg` values(NULL,'	Como Ã© conhecido o artista que produz grafites no cenÃ¡rio urbano?	','	4	');
INSERT INTO `perg` values(NULL,'	O conjunto haploide de cromossomos Ã© chamado de:	','	0	');
INSERT INTO `perg` values(NULL,'	Marque a opÃ§Ã£o onde apenas estÃ£o listadas relaÃ§Ãµes desarmÃ´nicas.	','	2	');
INSERT INTO `perg` values(NULL,'	Para gerar o conhecimento filosÃ³fico Ã© essencial qual elemento?	','	3	');
INSERT INTO `perg` values(NULL,'	FilÃ³sofo que defendeu que todos os males foram ocasionaÂ­dos pelo surgimento da propriedade privada:	','	3	');
INSERT INTO `perg` values(NULL,'	O modelo de produÃ§Ã£o capitalista se desenvolveu fortemente na sociedade:	','	0	');
INSERT INTO `perg` values(NULL,'	â€œ____ dog is that?â€ â€œIt her dog.â€	','	1	');
INSERT INTO `perg` values(NULL,'	A vitamina D e o colesterol sÃ£o constituÃ­dos de:	','	3	');
INSERT INTO `perg` values(NULL,'	Tecido epitelial e tecido conjuntivo formam uma membrana chamada:	','	2	');
INSERT INTO `perg` values(NULL,'	_______________ Ã© observado nas regiÃµes da Terra situadas na penumbra da Lua	','	2	');
INSERT INTO `perg` values(NULL,'	Em qual das frases podemos identificar um exemplo de intertextualidade explÃ­cita:	','	2	');
INSERT INTO `perg` values(NULL,'	Na classificaÃ§Ã£o de Lineu antes da classe vem:	','	1	');
INSERT INTO `perg` values(NULL,'	What does â€œao redorâ€ mean?	','	2	');
INSERT INTO `perg` values(NULL,'	Como era a avaliaÃ§Ã£o de SÃ³crates sobre a democracia ateniense?	','	2	');
INSERT INTO `perg` values(NULL,'	Hobbes defendeu que tipo de governo?	','	4	');
INSERT INTO `perg` values(NULL,'	Quem sÃ£o Colombina e PierrÃ´?	','	3	');
INSERT INTO `perg` values(NULL,'	A base material Ã© formada de acordo com os modos como os indivÃ­duos produzem e trabalham em sociedade. Esse Ã© o conceito de:	','	0	');
INSERT INTO `perg` values(NULL,'	Mineral importante para o funcionamento da glÃ¢ndula tireoide e que Ã© encontrado misturado ao sal de cozinha.	','	2	');
INSERT INTO `perg` values(NULL,'	This copy is ______ the other one.	','	4	');
INSERT INTO `perg` values(NULL,'	The violin is _____ the cello.	','	0	');
INSERT INTO `perg` values(NULL,'	El verbo â€œencontramosâ€ estÃ¡ conjugado en el mismo tiempo y modo que:	','	0	');
INSERT INTO `perg` values(NULL,'	Marx construiu socialismo cientÃ­fico em conjunto com qual pensador?	','	2	');
INSERT INTO `perg` values(NULL,'	He dropped _____ bag.	','	0	');
INSERT INTO `perg` values(NULL,'	El artÃ­culo definido viene delante de un:	','	2	');
INSERT INTO `perg` values(NULL,'	Uma das principais consequÃªncias da Primeira Guerra Mundial foi:	','	1	');
INSERT INTO `perg` values(NULL,'	Qual o critÃ©rio de formaÃ§Ã£o das classes sociais segundo Marx?	','	0	');
INSERT INTO `perg` values(NULL,'	A Guerra da DevoluÃ§Ã£o ocorreu durante o reinado de:	','	2	');
INSERT INTO `perg` values(NULL,'	Identifique a Ãºnica alternativa que NÃƒO Ã© verdadeira em relaÃ§Ã£o Ã  Primeira Guerra Mundial:	','	0	');
INSERT INTO `perg` values(NULL,'	Como eram feitas as folhas no Egito?	','	2	');
INSERT INTO `perg` values(NULL,'	El artÃ­culo â€œlasâ€ podrÃ­a anteceder la palabra:	','	2	');
INSERT INTO `perg` values(NULL,'	A cultura erudita Ã© transmitida por meio de quÃª?	','	0	');
INSERT INTO `perg` values(NULL,'	She lives _____ Italy.	','	4	');
INSERT INTO `perg` values(NULL,'	Which of the options below means â€œembaixoâ€?	','	2	');
INSERT INTO `perg` values(NULL,'	The boys are playing soccer.â€ The bold expression can be replaced by which of the options below?	','	3	');
INSERT INTO `perg` values(NULL,'	â€œMientrasâ€ significa:	','	2	');
INSERT INTO `perg` values(NULL,'	Karl Marx argumentou que as reflexÃµes filosÃ³ficas devem partir do ser concreto  formulando uma posiÃ§Ã£o:	','	1	');
INSERT INTO `perg` values(NULL,'	Camada germinativa que determina os tecidos de revestimento e componentes dos sistemas digestÃ³rio e respiratÃ³rio.	','	4	');
INSERT INTO `perg` values(NULL,'	Ao criar as bases de seu materialismo  Marx exerce uma crÃ­tica ao:	','	1	');
INSERT INTO `perg` values(NULL,'	I wake up _____ 8 a.m. every day.	','	0	');
INSERT INTO `perg` values(NULL,'	Quem Ã© James Cameron?	','	0	');
INSERT INTO `perg` values(NULL,'	A maior das contribuiÃ§Ãµes positivistas no Brasil talvez tenha sido a participaÃ§Ã£o de positivistas brasileiros no:	','	0	');
INSERT INTO `perg` values(NULL,'	We bought _____ house in the city.	','	3	');
INSERT INTO `perg` values(NULL,'	We love ____.	','	3	');
INSERT INTO `perg` values(NULL,'	All the verbs below follow the same pattern  except for	','	2	');
INSERT INTO `perg` values(NULL,'	Instead ofâ€ significa	','	2	');
INSERT INTO `perg` values(NULL,'	Em relaÃ§Ã£o aos conceitos de movimento e repouso	','	0	');
INSERT INTO `perg` values(NULL,'	Oliver is ______ his girlfriend.	','	0	');
INSERT INTO `perg` values(NULL,'	A Contrarreforma tinha como objetivo:	','	4	');
INSERT INTO `perg` values(NULL,'	AformaÃ§Ã£o da camada de ozÃ´nio foi possÃ­vel graÃ§as a presenÃ§a do _______________ na atmosfera. O gÃ¡s que substitui o espaÃ§o em branco Ã©:	','	4	');
