INSERT INTO `resp` values(NULL, '	hache	','	zeta	','	uve doble	','	equis	','	eÃ±e	',	4	,'	1	');
INSERT INTO `resp` values(NULL, '	criou as Companhias de ComÃ©rcio	','	aboliu a taxaÃ§Ã£o do ouro no Brasil	','	proibiu a instituiÃ§Ã£o da Derrama	','	perseguiu os â€œcristÃ£os novosâ€	','	foi um grande rei de Portugal	',	0	,'	2	');
INSERT INTO `resp` values(NULL, '	socialista	','	fisiocrata	','	comunista	','	positivista	','	anarquista	',	1	,'	3	');
INSERT INTO `resp` values(NULL, '	monÃ¡rquico	','	autoritÃ¡rio	','	ditatorial	','	democrÃ¡tico	','	platÃ´nico	',	3	,'	4	');
INSERT INTO `resp` values(NULL, '	Absolutismo iluminado	','	Despotismo esclarecido	','	Antigo Regime esclarecido	','	Monarquia iluminada	','	Nobreza esclarecida	',	1	,'	5	');
INSERT INTO `resp` values(NULL, '	Terra entre mares	','	Terra seca	','	Terra entre rios	','	Terra fÃ©rtil	','	Terra molhada	',	2	,'	6	');
INSERT INTO `resp` values(NULL, '	catabolismo	','	fermentaÃ§Ã£o lÃ¡ctica	','	anabolismo	','	fermentaÃ§Ã£o alcoÃ³lica	','	quimiossÃ­ntese	',	2	,'	7	');
INSERT INTO `resp` values(NULL, '	12 s	','	24 s	','	11 s	','	14 s	','	20 s	',	1	,'	8	');
INSERT INTO `resp` values(NULL, '	como juridicamente confiÃ¡veis	','	como juridicamente leais	','	como juridicamente normais	','	como juridicamente diferentes	','	como juridicamente iguais	',	4	,'	9	');
INSERT INTO `resp` values(NULL, '	a temperatura da Terra era muito baixa.	','	a temperatura da Terra era muito alta.	','	muitos asteroides colidiam na Terra.	','	muitos asteroides colidiam na Terra.	','	Os gases e as partÃ­culas liberados pelos vulcÃµes ficavam retidos na atmosfera.	',	0	,'	10	');
INSERT INTO `resp` values(NULL, '	Esposa	','	Noiva	','	Filha	','	Cunhada	','	CrianÃ§a	',	1	,'	11	');
INSERT INTO `resp` values(NULL, '	Tese	','	AntÃ­tese	','	SÃ­ntese	','	Ironia	','	SensÃ­vel	',	2	,'	12	');
INSERT INTO `resp` values(NULL, '	Stuart	','	Tudor	','	Lancaster	','	York	','	Windsor	',	1	,'	13	');
INSERT INTO `resp` values(NULL, '	BÃ©lgica.	','	Brasil.	','	Alemanha.	','	ItÃ¡lia.	','	Espanha.	',	1	,'	14	');
INSERT INTO `resp` values(NULL, '	very smart two	','	two very smart	','	very two smart	','	some very two smart	','	some smart very two	',	1	,'	15	');
INSERT INTO `resp` values(NULL, '	done.	','	did.	','	does.	','	doed.	','	did do.	',	1	,'	16	');
INSERT INTO `resp` values(NULL, '	Reino Unido	','	FranÃ§a	','	Alemanha	','	EUA	','	URSS	',	3	,'	17	');
INSERT INTO `resp` values(NULL, '	a descamaÃ§Ã£o.	','	a perda excessiva de Ã¡gua.	','	a falta de elasticidade.	','	a deficiÃªncia na produÃ§Ã£o de melanina.	','	que a pele se rasgue quando esticada	',	1	,'	18	');
INSERT INTO `resp` values(NULL, '	estar	','	ir	','	imaginar	','	pensar	','	andar	',	1	,'	19	');
INSERT INTO `resp` values(NULL, '	a polÃ­tica dos cercamentos	','	a instituiÃ§Ã£o do Bill of Rights	','	o lanÃ§amento do Ato de NavegaÃ§Ã£o	','	a vitÃ³ria contra a FranÃ§a, na Guerra dos Cem Anos	','	a restauraÃ§Ã£o da monarquia, com Carlos II	',	2	,'	20	');
INSERT INTO `resp` values(NULL, '	Carbono	','	HidrogÃªnio	','	NitrogÃªnio	','	FÃ³sforo	','	SilÃ­cio	',	4	,'	21	');
INSERT INTO `resp` values(NULL, '	FranÃ§a	','	Inglaterra	','	Espanha	','	Portugal	','	Alemanha	',	3	,'	22	');
INSERT INTO `resp` values(NULL, '	Anais da HistÃ³ria EconÃ´mica e Social.	','	PeriÃ³dico FrancÃªs Anti-positivista.	','	Anais da HistÃ³ria Anti-positivista.	','	Revista da HistÃ³ria Anti-positivista.	','	Revista de HistÃ³ria EconÃ´mica.	',	0	,'	23	');
INSERT INTO `resp` values(NULL, '	ontem.	','	hoje cedo.	','	amanhÃ£.	','	antes de ontem.	','	ontem Ã  noite.	',	3	,'	24	');
INSERT INTO `resp` values(NULL, '	parasitismo.	','	mutualismo.	','	predaÃ§Ã£o.	','	sociedade.	','	epifitismo.	',	2	,'	25	');
INSERT INTO `resp` values(NULL, '	Bruces fingerprints	','	Brucesâ€™s fingerprints	','	Bruceâ€™s fingerprints	','	Bruces fingerprintsâ€™	','	Bruce fingerprintâ€™s	',	2	,'	26	');
INSERT INTO `resp` values(NULL, '	Luz	','	Solar	','	Escola	','	Riso	','	Fala	',	3	,'	27	');
INSERT INTO `resp` values(NULL, '	ao se aquecer as Ã¡guas dos rios para aumentar a velocidade da decomposiÃ§Ã£o.	','	realizar o tratamento do esgoto antes do despejo nos rios e lagoas.	','	ao se adicionar bactÃ©rias anaerÃ³bicas Ã s Ã¡guas dos rios, jÃ¡ que elas sobrevivem sem oxigÃªnio.	','	substituindo-se produtos nÃ£o degradÃ¡veis por biodegradÃ¡veis.	','	diluindo-se o esgoto antes do seu despejo.	',	1	,'	28	');
INSERT INTO `resp` values(NULL, '	Com o novo e tecnolÃ³gico.	','	Com o tradicional e acadÃªmico.	','	Com o inovador e surpreendente.	','	Com o preconceito e a felicidade.	','	Com o claro e o escuro.	',	1	,'	29	');
INSERT INTO `resp` values(NULL, '	more warm than	','	the most warm	','	the warmest	','	the least warmest	','	warmer than	',	2	,'	30	');
INSERT INTO `resp` values(NULL, '	Por meio da exclusÃ£o das cores.	','	Por meio de combinaÃ§Ãµes entre as cores primÃ¡rias.	','	Por meio de combinaÃ§Ãµes entre as cores terciÃ¡rias.	','	Por meio da adiÃ§Ã£o da cor preta.	','	Por meio da subtraÃ§Ã£o da cor branca.	',	1	,'	31	');
INSERT INTO `resp` values(NULL, '	Bald	','	Young	','	Old	','	Red	','	Smart	',	0	,'	32	');
INSERT INTO `resp` values(NULL, '	Revistas.	','	Celular.	','	TelevisÃ£o.	','	Jornais.	','	Biscoito.	',	4	,'	33	');
INSERT INTO `resp` values(NULL, '	conhecer a si mesmo	','	questionar os sofistas	','	concordar com os sofistas	','	possuir dinheiro	','	garantir a democracia	',	0	,'	34	');
INSERT INTO `resp` values(NULL, '	Carlos I	','	Henrique IV	','	Henrique III	','	Jaime I	','	Jaime II	',	3	,'	35	');
INSERT INTO `resp` values(NULL, '	amensalismo.	','	comensalismo.	','	predaÃ§Ã£o.	','	mutualismo.	','	competiÃ§Ã£o.	',	2	,'	36	');
INSERT INTO `resp` values(NULL, '	famÃ­lia	','	felicidade	','	figo	','	foca	','	fogÃ£o	',	1	,'	37	');
INSERT INTO `resp` values(NULL, '	vitaminose.	','	hipervitaminose.	','	hipovitaminose.	','	megavitaminose.	','	supervitaminose.	',	2	,'	38	');
INSERT INTO `resp` values(NULL, '	Elizabeth I	','	LuÃ­s XIV	','	Joana I Grey	','	Alexandre II	','	Henrique VIII	',	4	,'	39	');
INSERT INTO `resp` values(NULL, '	Mussolini	','	Adolf Hitler	','	Otto Von Bismark	','	Guilherme II	','	Alexandre I	',	2	,'	40	');
INSERT INTO `resp` values(NULL, '	vitaminas, carboidratos e lipÃ­dios.	','	sais minerais, Ã¡gua e lipÃ­dios.	','	Ã¡gua, vitaminas e sais minerais.	','	Ã¡gua, carboidratos e vitaminas.	','	sais minerais, carboidratos e Ã¡gua.	',	2	,'	41	');
INSERT INTO `resp` values(NULL, '	silver old beautiful	','	beautiful silver old	','	beautiful old silver	','	silver beautiful old	','	old beautiful silver	',	2	,'	42	');
INSERT INTO `resp` values(NULL, '	the most exciting	','	more exciting	','	the more exciting	','	most exciting	','	most exciting than	',	0	,'	43	');
INSERT INTO `resp` values(NULL, '	as formas.	','	os sons.	','	as paisagens.	','	as pessoas.	','	as cores.	',	4	,'	44	');
INSERT INTO `resp` values(NULL, '	aves.	','	algas.	','	peixes.	','	insetos.	','	camarÃµes.	',	0	,'	45	');
INSERT INTO `resp` values(NULL, '	documentÃ¡rio.	','	pintura.	','	filme.	','	mÃºsica.	','	danÃ§a.	',	2	,'	46	');
INSERT INTO `resp` values(NULL, '	Semana de Arte Moderna	','	Ditadura civil-militar	','	Catequese dos povos indÃ­genas	','	ColonizaÃ§Ã£o de SÃ£o Paulo	','	ConstruÃ§Ã£o de igrejas	',	0	,'	47	');
INSERT INTO `resp` values(NULL, '	Cruzadas	','	Guerra dos Cem Anos	','	Guerra de Reconquista	','	Guerra das Duas Rosas	','	Conquista de Granada	',	0	,'	48	');
INSERT INTO `resp` values(NULL, '	ao invÃ©s de.	','	apesar de.	','	entretanto.	','	alÃ©m de.	','	assim como.	',	1	,'	49	');
INSERT INTO `resp` values(NULL, '	along	','	between	','	among	','	in front of	','	above	',	3	,'	50	');
INSERT INTO `resp` values(NULL, '	abandonar formas de pensar construÃ­das pelo senso comum	','	admitir ignorÃ¢ncia polÃ­tica	','	promover uma sequÃªncia de observaÃ§Ã£o	','	defender a continuidade do pensamento mitolÃ³gico	','	compreender o conhecimento formulado pelo senso comum	',	0	,'	51	');
INSERT INTO `resp` values(NULL, '	This pen is mine.	','	Those cars are theirs.	','	That is hers bag.	','	This money is ours.	','	My name is the same as hers.	',	2	,'	52	');
INSERT INTO `resp` values(NULL, '	A heranÃ§a cultural prÃ©-colombiana.	','	A religiosidade catÃ³lica.	','	O ideal de beleza grego.	','	A abstraÃ§Ã£o.	','	O delÃ­rio.	',	0	,'	53	');
INSERT INTO `resp` values(NULL, '	AmÃ©rica	','	Ãsia.	','	Europa.	','	Oceania.	','	Ãfrica.	',	4	,'	54	');
INSERT INTO `resp` values(NULL, '	colÃ´nia e sociedade.	','	competiÃ§Ã£o e canibalismo.	','	mutualismo e protocooperaÃ§Ã£o.	','	epifitismo e sociedade.	','	parasitismo e colÃ´nia.	',	1	,'	55	');
INSERT INTO `resp` values(NULL, '	happier as.	','	happier than.	','	happy than.	','	happy as.	','	less happy than.	',	1	,'	56	');
INSERT INTO `resp` values(NULL, '	verÃ£o â€“ outono.	','	inverno â€“ verÃ£o.	','	inverno â€“ outono.	','	verÃ£o â€“ inverno.	','	primavera â€“ outono.	',	3	,'	57	');
INSERT INTO `resp` values(NULL, '	cientÃ­ficos.	','	alimentÃ­cios.	','	utilitÃ¡rios.	','	gastronÃ´micos.	','	estÃ©ticos.	',	2	,'	58	');
INSERT INTO `resp` values(NULL, '	Lo bueno de la vida es viajar.	','	Necesito de un tiempo para pensar.	','	Las cosas no estÃ¡n buenas.	','	Un dÃ­a voy a Paris.	','	ComprÃ© unos vestidos.	',	1	,'	59	');
INSERT INTO `resp` values(NULL, '	Para algumas correntes da geografia, pode ser entendido(a) como uma classe de Ã¡rea, que pode apresentar grande uniformidade interna e grandes diferenÃ§as quando comparada a outras Ã¡reas.	','	As relaÃ§Ãµes de poder construÃ­das e estabelecidas sÃ£o determinantes para a sua definiÃ§Ã£o e delimitaÃ§Ã£o.	','	Ã‰, numa determinada porÃ§Ã£o do espaÃ§o, o resultado da combinaÃ§Ã£o dinÃ¢mica, portanto instÃ¡vel, de elementos fÃ­sicos, biolÃ³gicos e antrÃ³picos que, reagindo dialeticamente, uns sobre os outros, fazem da paisagem um conjunto indissociÃ¡vel, em perpÃ©tua evoluÃ§Ã£o.	','	Ã‰ marcado(a) pelas relaÃ§Ãµes de consenso, conflito, dominaÃ§Ã£o e resistÃªncia, onde se cria identidade e onde se vive.	','	Conjunto indissociÃ¡vel de sistemas de objetos e sistemas de aÃ§Ãµes, que procura revelar as prÃ¡ticas sociais dos diferentes grupos.	',	1	,'	60	');
INSERT INTO `resp` values(NULL, '	que nÃ£o precisam de refrigeraÃ§Ã£o.	','	que podem causar infecÃ§Ãµes.	','	sujeitos a estragar com rapidez se nÃ£o forem empregados processos suplementares para a sua conservaÃ§Ã£o.	','	que nÃ£o necessitam de processos especiais para conservaÃ§Ã£o.	','	requeridos em grandes quantidades diariamente.	',	2	,'	61	');
INSERT INTO `resp` values(NULL, '	escultores.	','	danÃ§arinos.	','	pintores.	','	dramaturgos.	','	escritores.	',	2	,'	62	');
INSERT INTO `resp` values(NULL, '	parceria	','	uniÃ£o	','	confronto	','	solidariedade	','	dependÃªncia	',	0	,'	63	');
INSERT INTO `resp` values(NULL, '	Natal.	','	Novela.	','	Nuvem.	','	Neve.	','	Madeira.	',	4	,'	64	');
INSERT INTO `resp` values(NULL, '	more intelligenter	','	intelligenter as	','	intelligent as	','	more intelligent than	','	more intelligent	',	3	,'	65	');
INSERT INTO `resp` values(NULL, '	Fuese	','	EstÃ©	','	Sabe	','	Quisiera	','	Sepa	',	2	,'	66	');
INSERT INTO `resp` values(NULL, '	Duas consoantes.	','	Uma consoante.	','	TrÃªs consoantes.	','	Sete consoantes.	','	Nenhuma consoante.	',	2	,'	67	');
INSERT INTO `resp` values(NULL, '	Inglaterra.	','	Espanha.	','	FranÃ§a.	','	Brasil.	','	Estados Unidos.	',	2	,'	68	');
INSERT INTO `resp` values(NULL, '	ahÃ­ â€“ hoy â€“ ayer	','	muy â€“ probablemente â€“ despacio	','	claro â€“ quizÃ¡ â€“ tal vez	','	ahora â€“ anteanoche â€“ aÃºn	','	hoy â€“ luego â€“ tampoco	',	3	,'	69	');
INSERT INTO `resp` values(NULL, '	Hobbes	','	Galileu	','	SÃ³crates	','	Bauman	','	Descartes	',	3	,'	70	');
INSERT INTO `resp` values(NULL, '	DanÃ§a.	','	MÃºsica.	','	Literatura.	','	Pintura.	','	Escultura.	',	2	,'	71	');
INSERT INTO `resp` values(NULL, '	cascavel	','	tartaruga	','	rÃ£	','	barata	','	alga	',	4	,'	72	');
INSERT INTO `resp` values(NULL, '	PÃ¡ssaros.	','	Flores.	','	Bailarinas.	','	Paisagens.	','	Animais.	',	2	,'	73	');
INSERT INTO `resp` values(NULL, '	Marx	','	Comte	','	Proudhon	','	Saint-Simon	','	Bakunin	',	2	,'	74	');
INSERT INTO `resp` values(NULL, '	Possuem carioteca	','	NÃ£o possuem carioteca	','	NÃ£o possuem membrana	','	Possuem apenas citoplasma	','	NÃ£o possuem citoplasma	',	0	,'	75	');
INSERT INTO `resp` values(NULL, '	a classe	','	a ordem	','	a famÃ­lia	','	o reino	','	o gÃªnero	',	0	,'	76	');
INSERT INTO `resp` values(NULL, '	debemos	','	debemos	','	debÃ­amos	','	debiÃ©semos	','	debiesen	',	1	,'	77	');
INSERT INTO `resp` values(NULL, '	Augusto Comte	','	Karl Marx	','	Friedrich Hegel	','	Friedrich Engels	','	RenÃ© Descartes	',	0	,'	78	');
INSERT INTO `resp` values(NULL, '	Registraram os momentos e mudanÃ§as ocorridos no Brasil.	','	Trouxeram novos movimentos artÃ­sticos para o Brasil, como o RococÃ³.	','	Sabiam que queriam voltar logo para casa.	','	Estenderam seus ensinamentos para a Ã¡rea da saÃºde tambÃ©m.	','	Buscaram se aproximar de novos movimentos religiosos.	',	0	,'	79	');
INSERT INTO `resp` values(NULL, '	more short than	','	shorter than	','	the most short	','	the shortest	','	shortest than	',	3	,'	80	');
INSERT INTO `resp` values(NULL, '	as decisÃµes tomadas em pÃºblico	','	ao conhecimento relativo	','	ao pensamento concreto	','	a defesa dos mitos	','	a valorizaÃ§Ã£o da natureza	',	1	,'	81	');
INSERT INTO `resp` values(NULL, '	artistas famosos.	','	artistas anÃ´nimos.	','	artistas da TV.	','	artistas da vanguarda.	','	artistas emergentes.	',	1	,'	82	');
INSERT INTO `resp` values(NULL, '	Imamanuel Kant e Karl Marx	','	Karl Marx e Friedrich Engels	','	Friedrich Engels e Carl GrÃ¼nberg	','	Carl GrÃ¼nberg e Friedrich Nietzsche	','	a)Â Â Â  Friedrich Nietzsche e Theodor Adorno	',	1	,'	83	');
INSERT INTO `resp` values(NULL, '	mine	','	my	','	hers	','	theirs	','	ours	',	1	,'	84	');
INSERT INTO `resp` values(NULL, '	Carlos II buscava favorecer os catÃ³licos	','	o Parlamento foi favorÃ¡vel, pois era formado por catÃ³licos	','	o rei foi contra, pois era puritano	','	o rei e o Parlamento eram favorÃ¡veis	','	era uma maneira de o rei favorecer os puritanos	',	0	,'	85	');
INSERT INTO `resp` values(NULL, '	M	','	m	','	L	','	G	','	F	',	1	,'	86	');
INSERT INTO `resp` values(NULL, '	more helpful	','	helpful	','	helpfuler	','	more helpfuler	','	the helpfulest	',	0	,'	87	');
INSERT INTO `resp` values(NULL, '	o JapÃ£o teve de conceder o controle sobre a Coreia para a RÃºssia	','	o JapÃ£o reconhece a vitÃ³ria da RÃºssia na guerra entre ambas	','	o governo russo teve que reconhecer a soberania japonesa na Coreia	','	ambos os paÃ­ses em guerra tiveram de reconhecer a independÃªncia da Coreia	','	JapÃ£o e RÃºssia se submetiam ao ImpÃ©rio ChinÃªs	',	2	,'	88	');
INSERT INTO `resp` values(NULL, '	Os bandeirantes.	','	A famÃ­lia real.	','	Os jesuÃ­tas.	','	A corte.	','	Os Ã­ndios prÃ©-colombianos.	',	2	,'	89	');
INSERT INTO `resp` values(NULL, '	coesÃ£o social	','	solidariedade mecÃ¢nica	','	solidariedade orgÃ¢nica	','	luta de classes	','	anomia social	',	3	,'	90	');
INSERT INTO `resp` values(NULL, '	Amoritas	','	AssÃ­rios	','	Hicsos	','	Caldeus	','	AcÃ¡dios	',	4	,'	91	');
INSERT INTO `resp` values(NULL, '	leguminosas.	','	hortaliÃ§as.	','	carnes vermelhas.	','	Ã¡gua.	','	frutos do mar.	',	3	,'	92	');
INSERT INTO `resp` values(NULL, '	Paz Armada	','	Guerra de Trincheiras	','	Guerra de Movimento	','	Guerra Fria	','	Guerra RelÃ¢mpago	',	2	,'	93	');
INSERT INTO `resp` values(NULL, '	as longest as	','	not so long as	','	longest as	','	longer as	','	as long than	',	1	,'	94	');
INSERT INTO `resp` values(NULL, '	little cute cottage	','	cute little cottage	','	cottage little cute	','	cottage cute little	','	little cottage cute	',	1	,'	95	');
INSERT INTO `resp` values(NULL, '	A revoluÃ§Ã£o mexicana e as vanguardas europeias.	','	Os movimentos sociais dos Estados Unidos.	','	A arte africana.	','	Os estudos de psicanÃ¡lise de Freud.	','	A Segunda Guerra Mundial.	',	0	,'	96	');
INSERT INTO `resp` values(NULL, '	Orar.	','	Cultivar.	','	Apreciar.	','	Brincar.	','	Completar.	',	1	,'	97	');
INSERT INTO `resp` values(NULL, '	auxiliar a produÃ§Ã£o de energia.	','	defender o corpo contra ameaÃ§as.	','	formar uma reserva de energia.	','	regular a digestÃ£o.	','	compor ossos e dentes, alÃ©m de atuar na atividade dos mÃºsculos.	',	4	,'	98	');
INSERT INTO `resp` values(NULL, '	surgisse a fotografia.	','	a arte se mantivesse no passado.	','	os artistas se revoltassem contra a ciÃªncia.	','	as pessoas parassem de fazer arte.	','	a sociedade negasse a pintura.	',	0	,'	99	');
INSERT INTO `resp` values(NULL, '	Primitivo	','	Capitalista	','	Escravista	','	Feudalista	','	Comunista	',	1	,'	100	');
INSERT INTO `resp` values(NULL, '	da psicologia freudiana	','	da realidade virtual ao seu redor	','	da funÃ§Ã£o na sociedade	','	do grau de evoluÃ§Ã£o das sociedades	','	da estrutura que estÃ¡ inserido	',	4	,'	101	');
INSERT INTO `resp` values(NULL, '	Deus no centro do universo	','	a Igreja no centro do universo	','	o homem no centro do universo	','	o rei no centro do universo	','	a BÃ­blia no centro do universo	',	0	,'	102	');
INSERT INTO `resp` values(NULL, '	Shakespeare.	','	Jaime.	','	Stuart.	','	Rafael.	','	MoliÃ¨re.	',	4	,'	103	');
INSERT INTO `resp` values(NULL, '	anomia social	','	materialismo histÃ³rico	','	solidariedade social	','	aÃ§Ã£o social	','	fato social	',	0	,'	104	');
INSERT INTO `resp` values(NULL, '	CangaÃ§o	','	EsquadrÃ£o Prestes	','	Coluna Prestes	','	Coluna LuÃ­s Carlos	','	PelotÃ£o dos Tenentes	',	2	,'	105	');
INSERT INTO `resp` values(NULL, '	navio.	','	trem.	','	bicicleta.	','	barco.	','	metrÃ´.	',	0	,'	106	');
INSERT INTO `resp` values(NULL, '	no estÃ´mago.	','	no intestino delgado.	','	na faringe.	','	no intestino grosso.	','	no fÃ­gado.	',	3	,'	107	');
INSERT INTO `resp` values(NULL, '	Marechal Hermes da Fonseca	','	Marechal Deodoro da Fonseca	','	Marechal Floriano Peixoto	','	Marechal Rondon	','	LuÃ­s Carlos Prestes	',	2	,'	108	');
INSERT INTO `resp` values(NULL, '	Ã‰mile Durkheim	','	Auguste Comte	','	Arthur Schopenhauer	','	Immanuel Kant	','	David Hume	',	2	,'	109	');
INSERT INTO `resp` values(NULL, '	the most long	','	the longest	','	longest	','	longest than	','	longer	',	1	,'	110	');
INSERT INTO `resp` values(NULL, '	translaÃ§Ã£o.	','	nidaÃ§Ã£o.	','	compactaÃ§Ã£o.	','	rotaÃ§Ã£o.	','	traduÃ§Ã£o.	',	0	,'	111	');
INSERT INTO `resp` values(NULL, '	vivas	','	haces	','	comÃ¡is	','	quisieran	','	sentÃ­a	',	1	,'	112	');
INSERT INTO `resp` values(NULL, '	antropologia e biologia	','	ciÃªncia polÃ­tica e biologia	','	antropologia e ciÃªncia polÃ­tica	','	antropologia e economia	','	economia e biologia	',	2	,'	113	');
INSERT INTO `resp` values(NULL, '	buscarem uma harmonia perfeita	','	idealizarem uma sociedade desigual	','	refletirem sem base intelectual	','	formarem um grupo de estudos coeso	','	residirem na cidade de utopia	',	0	,'	114	');
INSERT INTO `resp` values(NULL, '	Lei da identidade	','	Lei da lÃ³gica	','	Lei polÃ­tica	','	Lei da nÃ£o-contradiÃ§Ã£o	','	Lei dos trÃªs estados	',	4	,'	115	');
INSERT INTO `resp` values(NULL, '	Lo que sabemos hacer	','	Lo que podemos hacer	','	Cualidades inherentes	','	CaracterÃ­stica menos permanente	','	Cualidad adquirida	',	4	,'	116	');
INSERT INTO `resp` values(NULL, '	blÃ¡sticos.	','	diblÃ¡sticos.	','	triblÃ¡sticos.	','	quadriblÃ¡sticos.	','	pentablÃ¡sticos.	',	2	,'	117	');
INSERT INTO `resp` values(NULL, '	What	','	Where	','	When	','	How	','	Why	',	3	,'	118	');
INSERT INTO `resp` values(NULL, '	When	','	Where	','	What	','	How	','	Who	',	2	,'	119	');
INSERT INTO `resp` values(NULL, '	perspectiva.	','	hachura.	','	chiaroscuro.	','	aquarela.	','	tÃªmpera.	',	2	,'	120	');
INSERT INTO `resp` values(NULL, '	bactÃ©ria	','	pitangueira	','	craca	','	tamanduÃ¡	','	jiboia	',	0	,'	121	');
INSERT INTO `resp` values(NULL, '	Roupas.	','	MÃ¡scaras	','	Paisagens.	','	Animais.	','	Pessoas.	',	1	,'	122	');
INSERT INTO `resp` values(NULL, '	espiritualismo histÃ³rico dialÃ©tico	','	materialismo histÃ³rico dialÃ©tico	','	positivismo histÃ³rico dialÃ©tico	','	criticismo histÃ³rico dialÃ©tico	','	realismo histÃ³rico dialÃ©tico	',	1	,'	123	');
INSERT INTO `resp` values(NULL, '	Genro	','	Nora	','	Enteado	','	Filhos	','	Pai	',	3	,'	124	');
INSERT INTO `resp` values(NULL, '	igual	','	menor	','	maior	','	melhor	','	pior	',	2	,'	125	');
INSERT INTO `resp` values(NULL, '	continuidade total	','	ruptura parcial	','	ruptura total	','	imparcialidade	','	continuidade parcial	',	2	,'	126	');
INSERT INTO `resp` values(NULL, '	Um tradutor.	','	Um pintor.	','	Um gravurista.	','	Um danÃ§arino.	','	Um dramaturgo.	',	1	,'	127	');
INSERT INTO `resp` values(NULL, '	Revolta da Armada	','	Revolta da Chibata	','	Revolta da Vacina	','	Revolta dos MalÃªs	','	InconfidÃªncia Mineira	',	1	,'	128	');
INSERT INTO `resp` values(NULL, '	stepbrother.	','	stepmother.	','	stepsister.	','	wife.	','	groom.	',	2	,'	129	');
INSERT INTO `resp` values(NULL, '	of	','	from	','	to	','	in	','	at	',	3	,'	130	');
INSERT INTO `resp` values(NULL, '	mesmo epÃ­teto especÃ­fico	','	mesmo gÃªnero	','	mesmo gÃªnero e epÃ­teto especÃ­fico	','	famÃ­lia diferente	','	reino diferente	',	1	,'	131	');
INSERT INTO `resp` values(NULL, '	352 dias, 6 horas e 48 minutos.	','	365 dias, 6 horas e 48 minutos.	','	266 dias, 4 horas e 48 minutos.	','	127 dias, 6 horas e 58 minutos.	','	326 dias, 6 horas e 48 minutos.	',	1	,'	132	');
INSERT INTO `resp` values(NULL, '	AdaptaÃ§Ãµes	','	InadaptaÃ§Ã£o	','	Inconsciente	','	Medos	','	Fisicamente	',	0	,'	133	');
INSERT INTO `resp` values(NULL, '	the hottest.	','	hotier.	','	hotter than.	','	hot than.	','	as hot as.	',	2	,'	134	');
INSERT INTO `resp` values(NULL, '	relativiza o conhecimento	','	valoriza a democracia	','	introduz uma nova maneira de pensar	','	defende o pensamento dos sofistas	','	entra em conflito com PlatÃ£o	',	2	,'	135	');
INSERT INTO `resp` values(NULL, '	Ã³leos e manteigas.	','	Ã¡gua e vitaminas.	','	vitaminas e Ã³leos.	','	pÃ£es e massas.	','	pÃ£es e Ã³leos.	',	3	,'	136	');
INSERT INTO `resp` values(NULL, '	RevoluÃ§Ã£o Francesa	','	RevoluÃ§Ã£o Russa	','	RevoluÃ§Ã£o Mexicana	','	RevoluÃ§Ã£o Iraniana	','	RevoluÃ§Ã£o Gloriosa	',	1	,'	137	');
INSERT INTO `resp` values(NULL, '	noÃ§Ã£o de regresso	','	dependÃªncia econÃ´mica	','	ilusÃ£o	','	razÃ£o	','	religiÃ£o	',	3	,'	138	');
INSERT INTO `resp` values(NULL, '	o colonialismo	','	a RevoluÃ§Ã£o Industrial	','	a RevoluÃ§Ã£o Inglesa	','	a RevoluÃ§Ã£o Francesa	','	a R\evoluÃ§Ã£o Russa	',	1	,'	139	');
INSERT INTO `resp` values(NULL, '	a vontade de cada um.	','	o contexto social.	','	as leis.	','	as ordens.	','	as paisagens.	',	1	,'	140	');
INSERT INTO `resp` values(NULL, '	dos consumidores primÃ¡rios.	','	consumidores secundÃ¡rios.	','	produtores.	','	consumidores terciÃ¡rios.	','	decompositores.	',	2	,'	141	');
INSERT INTO `resp` values(NULL, '	parasitismo.	','	inquilinismo.	','	amensalismo.	','	epifitismo.	','	canibalismo.	',	0	,'	142	');
INSERT INTO `resp` values(NULL, '	ironia	','	indagaÃ§Ã£o	','	induÃ§Ã£o	','	exortaÃ§Ã£o	','	maiÃªutica	',	3	,'	143	');
INSERT INTO `resp` values(NULL, '	estÃ´mago.	','	esÃ´fago.	','	intestino grosso.	','	faringe.	','	intestino delgado.	',	2	,'	144	');
INSERT INTO `resp` values(NULL, '	least interesting	','	less interesting	','	as interestinger as	','	less interesting than	','	interesting as	',	3	,'	145	');
INSERT INTO `resp` values(NULL, '	their	','	his	','	its	','	her	','	my	',	3	,'	146	');
INSERT INTO `resp` values(NULL, '	1986	','	1976	','	1966	','	1956	','	1946	',	4	,'	147	');
INSERT INTO `resp` values(NULL, '	14 de dezembro.	','	20 de dezembro.	','	21 de dezembro.	','	22 de dezembro.	','	23 de dezembro.	',	2	,'	148	');
INSERT INTO `resp` values(NULL, '	a tradiÃ§Ã£o.	','	o antigo.	','	o moralismo.	','	as mÃ¡quinas.	','	a lentidÃ£o.	',	3	,'	149	');
INSERT INTO `resp` values(NULL, '	polipeptÃ­dio.	','	multipeptÃ­deo.	','	dipeptÃ­deo.	','	tripeptÃ­deo.	','	pentapeptÃ­deo.	',	0	,'	150	');
INSERT INTO `resp` values(NULL, '	BonÃ©	','	Beber	','	Batida	','	Tempo	','	Beto	',	3	,'	151	');
INSERT INTO `resp` values(NULL, '	womanâ€™s boyfriendâ€™s	','	womansâ€™ boyfriends	','	womenâ€™s boyfriends	','	womensâ€™ boyfriendâ€™s	','	womens boyfriendsâ€™	',	2	,'	152	');
INSERT INTO `resp` values(NULL, '	22 cromossomos	','	24 cromossomos	','	42 cromossomos	','	46 cromossomos	','	21 cromossomos	',	3	,'	153	');
INSERT INTO `resp` values(NULL, '	hers	','	mine	','	yours	','	her	','	theirs	',	3	,'	154	');
INSERT INTO `resp` values(NULL, '	logos	','	cosmo	','	archÃ©	','	mythos	','	physis	',	2	,'	155	');
INSERT INTO `resp` values(NULL, '	capitalismo	','	socialismo	','	comunismo	','	mercantilismo	','	anarquismo	',	3	,'	156	');
INSERT INTO `resp` values(NULL, '	Colher	','	Centro	','	Casa	','	Encolher	','	Bem	',	4	,'	157	');
INSERT INTO `resp` values(NULL, '	Bramante.	','	Botticelli.	','	Bernini.	','	Palladio.	','	Brunelleschi.	',	1	,'	158	');
INSERT INTO `resp` values(NULL, '	cometas.	','	asteroides.	','	meteoros.	','	meteoritos.	','	fragmentos celestes.	',	1	,'	159	');
INSERT INTO `resp` values(NULL, '	as popular than	','	not so popular as	','	popularer than	','	popular as	','	not popular	',	1	,'	160	');
INSERT INTO `resp` values(NULL, '	observaÃ§Ã£o	','	comparaÃ§Ã£o	','	experimentaÃ§Ã£o	','	hedonismo	','	empirismo	',	3	,'	161	');
INSERT INTO `resp` values(NULL, '	Tratado de Versalhes	','	Tratado de Saint-Germain	','	Tratado de Neuilly	','	Tratado de SÃ¨vres	','	Tratado de Trianon	',	0	,'	162	');
INSERT INTO `resp` values(NULL, '	RazÃµes histÃ³ricas	','	Sementes histÃ³ricas	','	Fontes histÃ³ricas	','	Agentes histÃ³ricos	','	Origens histÃ³ricas	',	2	,'	163	');
INSERT INTO `resp` values(NULL, '	SÃ­ntese	','	AntÃ­tese	','	Tese	','	Ironia	','	MaiÃªutica	',	0	,'	164	');
INSERT INTO `resp` values(NULL, '	17,3 bilhÃµes de anos.	','	13,7 bilhÃµes de anos.	','	20,4 bilhÃµes de anos.	','	10,7 bilhÃµes de anos.	','	8, 3 bilhÃµes de anos.	',	1	,'	165	');
INSERT INTO `resp` values(NULL, '	Idealismo.	','	Academicismo.	','	Busca pela beleza ideal.	','	Busca pela beleza ideal.	','	AbstraÃ§Ã£o.	',	3	,'	166	');
INSERT INTO `resp` values(NULL, '	happier	','	happiest	','	the happier	','	happier than	','	the happiest	',	4	,'	167	');
INSERT INTO `resp` values(NULL, '	the coldest	','	coldest	','	colder	','	the colder	','	the coldest than	',	0	,'	168	');
INSERT INTO `resp` values(NULL, '	to	','	in	','	at	','	on	','	for	',	0	,'	169	');
INSERT INTO `resp` values(NULL, '	liberdade de expressÃ£o	','	direito de ir e vir	','	acesso a propriedade privada	','	direito Ã  liberdade individual	','	direito ao voto	',	4	,'	170	');
INSERT INTO `resp` values(NULL, '	Lugar onde os limites territoriais ainda sÃ£o questionÃ¡veis, ou onde hÃ¡ Ã¡reas que sofrem arbitrariedade de paÃ­ses fronteiriÃ§os.	','	Lugar onde os limites territoriais sÃ£o conhecidos por todos os paÃ­ses, internacionalmente.	','	Neste tipo de fronteira nÃ£o hÃ¡ uma definiÃ§Ã£o exata que separe os dois territÃ³rios.	','	Linha convencional que marca os confins de um Estado, marcam a soberania de um paÃ­s.	','	Corresponde a divisÃ£o entre uma unidade territorial e outra, geralmente entre dois paÃ­ses.	',	1	,'	171	');
INSERT INTO `resp` values(NULL, '	La madre de tu novia estÃ¡ aquÃ­.	','	Miguel no fue aprobado.	','	No aguanto mÃ¡s estar lejos de ti.	','	Nos vemos en algunos dÃ­as.	','	Necesito de unos calcetines nuevos.	',	4	,'	172	');
INSERT INTO `resp` values(NULL, '	A velocidade.	','	A verticalidade.	','	A fotografia.	','	O excesso de cores.	','	O excesso de fantasia.	',	1	,'	173	');
INSERT INTO `resp` values(NULL, '	1845.	','	1823.	','	1825.	','	1821.	','	1897.	',	3	,'	174	');
INSERT INTO `resp` values(NULL, '	casamento civil igualitÃ¡rio	','	direito a vida polÃ­tica	','	direito ao divÃ³rcio	','	direito Ã  educaÃ§Ã£o igualitÃ¡ria	','	acesso ao mercado de trabalho	',	0	,'	175	');
INSERT INTO `resp` values(NULL, '	C	','	B	','	T	','	A	','	S	',	3	,'	176	');
INSERT INTO `resp` values(NULL, '	MiÃ©rcoles	','	Jueves	','	Martes	','	Viernes	','	Lunes	',	2	,'	177	');
INSERT INTO `resp` values(NULL, '	legislativo, presidencialista e judiciÃ¡rio	','	executivo, eleitoral e legislativo	','	monÃ¡rquico, executivo e judiciÃ¡rio	','	monÃ¡rquico, eleitoral e presidencialista	','	legislativo, executivo e judiciÃ¡rio	',	4	,'	178	');
INSERT INTO `resp` values(NULL, '	nutrientes.	','	alimentÃ­cios.	','	nutrimentos.	','	alimentares.	','	numarentes.	',	0	,'	179	');
INSERT INTO `resp` values(NULL, '	democracia inconstitucional	','	democracia autoritÃ¡ria	','	democracia direta	','	democracia cultural	','	democracia representativa	',	4	,'	180	');
INSERT INTO `resp` values(NULL, '	feudalismo	','	absolutismo	','	parlamentarismo	','	socialismo	','	repÃºblica	',	1	,'	181	');
INSERT INTO `resp` values(NULL, '	Giotto.	','	Rafael Sanzio.	','	Leonardo da Vinci.	','	El Greco.	','	Giorgio Vasari.	',	2	,'	182	');
INSERT INTO `resp` values(NULL, '	RegiÃ£o	','	Paisagem	','	EspaÃ§o	','	Lugar	','	TerritÃ³rio	',	4	,'	183	');
INSERT INTO `resp` values(NULL, '	competiÃ§Ã£o.	','	protocooperaÃ§Ã£o.	','	mutualismo.	','	amensalismo.	','	colÃ´nia.	',	4	,'	184	');
INSERT INTO `resp` values(NULL, '	How	','	Where	','	When	','	Why	','	What	',	4	,'	185	');
INSERT INTO `resp` values(NULL, '	mutualismo.	','	predaÃ§Ã£o.	','	competiÃ§Ã£o.	','	canibalismo.	','	epifitismo.	',	0	,'	186	');
INSERT INTO `resp` values(NULL, '	See you later.	','	Bye.	','	Whatâ€™s up?	','	Good night.	','	Goodbye.	',	2	,'	187	');
INSERT INTO `resp` values(NULL, '	ocorrÃªncia da RevoluÃ§Ã£o Socialista em territÃ³rio alemÃ£o	','	surgimento do Partido Nacional dos Trabalhadores AlemÃ£es (Partido Nazista)	','	surgimento do Partido Integralista AlemÃ£o	','	retorno ao regime monÃ¡rquico	','	guerra civil em territÃ³rio alemÃ£o	',	1	,'	188	');
INSERT INTO `resp` values(NULL, '	Martinho Lutero	','	Agostinho de Hipona	','	SÃ£o TomÃ¡s de Aquino	','	JoÃ£o Calvino	','	John Wesley	',	3	,'	189	');
INSERT INTO `resp` values(NULL, '	A	','	B12	','	C	','	K	','	E	',	2	,'	190	');
INSERT INTO `resp` values(NULL, '	Revolta da Armada	','	Revolta da Vacina	','	Guerra de Canudos	','	RevoluÃ§Ã£o Federalista	','	Revolta de Beckman	',	2	,'	191	');
INSERT INTO `resp` values(NULL, '	Todas as cores, ordenadas.	','	Nenhuma cor.	','	Elementos quÃ­micos.	','	Membros da famÃ­lia.	','	Participantes de um programa.	',	0	,'	192	');
INSERT INTO `resp` values(NULL, '	forte	','	intensa	','	violenta	','	viva	','	frÃ¡gil	',	4	,'	193	');
INSERT INTO `resp` values(NULL, '	113Â° F	','	131Â° F	','	133Â° F	','	116Â° F	','	117Â° F	',	0	,'	194	');
INSERT INTO `resp` values(NULL, '	vitaminas e Ã¡gua.	','	vitaminas e sais minerais.	','	sais minerais e carboidratos.	','	proteÃ­nas e sais minerais.	','	carboidratos e proteÃ­nas.	',	1	,'	195	');
INSERT INTO `resp` values(NULL, '	lei dos cinco estados	','	lei dos quatro estados	','	lei dos trÃªs estados	','	lei dos dois estados	','	lei sem estados	',	2	,'	196	');
INSERT INTO `resp` values(NULL, '	feudal	','	primitivo	','	asiÃ¡tico	','	escravista	','	capitalista	',	4	,'	197	');
INSERT INTO `resp` values(NULL, '	A black big	','	A new big	','	A big black	','	A old big	','	An big black	',	2	,'	198	');
INSERT INTO `resp` values(NULL, '	filÃ³sofo	','	sÃ¡bio	','	amante	','	amigo	','	ativista	',	1	,'	199	');
INSERT INTO `resp` values(NULL, '	1845.	','	1886.	','	1887.	','	1889.	','	1890.	',	3	,'	200	');
INSERT INTO `resp` values(NULL, '	Who	','	Whom	','	How	','	Whose	','	When	',	3	,'	201	');
INSERT INTO `resp` values(NULL, '	Belo Horizonte.	','	SÃ£o Paulo.	','	PetrÃ³polis.	','	Ubatuba.	','	BÃºzios.	',	2	,'	202	');
INSERT INTO `resp` values(NULL, '	direito polÃ­tico	','	direito social	','	direito civil	','	direito cultural	','	direito cidadÃ£o	',	0	,'	203	');
INSERT INTO `resp` values(NULL, '	F	','	f	','	G	','	P	','	L	',	0	,'	204	');
INSERT INTO `resp` values(NULL, '	Marxismo	','	Socialismo	','	Humanismo	','	EscolÃ¡stica	','	Contrarreforma	',	2	,'	205	');
INSERT INTO `resp` values(NULL, '	Quanto mais chove, mais alaga a rua.	','	A pressa Ã© a inimiga da refeiÃ§Ã£o.	','	Os jovens caminham perdidos pelas ruas.	','	Muitos perderam o foco.	','	Acima de tudo, tenha fÃ©!	',	1	,'	206	');
INSERT INTO `resp` values(NULL, '	Revolta da Armada	','	InconfidÃªncia Mineira	','	Revolta da Chibata	','	ConjuraÃ§Ã£o Baiana	','	RevoluÃ§Ã£o Farroupilha	',	2	,'	207	');
INSERT INTO `resp` values(NULL, '	â€œEstrutura idealizada na qual podemos realizar uma observaÃ§Ã£o de fenÃ´menos fÃ­sicos, e tambÃ©m descrevÃª-los e formular suas leis, podendo esta estrutura ser descrita abstratamente por um sistema de coordenadas espaciais e temporais.â€	','	â€œÃ‰ o percurso realizado por um determinado corpo no espaÃ§o, com base em um sistema de coordenadasâ€. Esse fragmento estÃ¡ relacionado a(ao).	','	Ã‰ uma grandeza vetorial definida como variaÃ§Ã£o de posiÃ§Ã£o de um objeto, de um lugar pra o outro.	','	Ã‰ a medida de separaÃ§Ã£o entre dois pontos quaisquer.	','	Uma dada situaÃ§Ã£o em que um objeto demonstra a mesma velocidade vetorial em relaÃ§Ã£o a um referencial, em resumo, nÃ£o modifica a distÃ¢ncia em relaÃ§Ã£o a um ponto referencial	',	1	,'	208	');
INSERT INTO `resp` values(NULL, '	MarÃ­a estÃ¡ decidida a dejarnos.	','	Pangamos los abrigos.	','	Vamos a encontrarnos allÃ¡.	','	No podrÃ­a ayudarte.	','	Deben de ser las ocho	',	2	,'	209	');
INSERT INTO `resp` values(NULL, '	cÃ©lulas adiposas	','	cÃ©lulas tegumentares	','	cÃ©lulas pavimentosas	','	cÃ©lulas germinativas	','	cÃ©lulas somÃ¡ticas	',	4	,'	210	');
INSERT INTO `resp` values(NULL, '	BiogÃªnese	','	GÃªnese	','	AbiogÃªnese	','	CriogÃªnese	','	Panspermia	',	2	,'	211	');
INSERT INTO `resp` values(NULL, '	JÃºpiter.	','	VÃªnus.	','	Saturno.	','	Urano.	','	Netuno.	',	1	,'	212	');
INSERT INTO `resp` values(NULL, '	a invenÃ§Ã£o das ferrovias	','	descoberta da energia elÃ©trica	','	expansÃ£o da industrializaÃ§Ã£o para outros paÃ­ses europeus e para os EUA	','	industrializaÃ§Ã£o apenas na Inglaterra	','	surgimento da engenharia genÃ©tica	',	4	,'	213	');
INSERT INTO `resp` values(NULL, '	umbra.	','	umbral.	','	penumbra.	','	penumbral.	','	eclipsa.	',	2	,'	214	');
INSERT INTO `resp` values(NULL, '	habitual.	','	revestimento.	','	estrutural.	','	preenchimento.	','	isolante.	',	2	,'	215	');
INSERT INTO `resp` values(NULL, '	heliocentrismo	','	geocentrismo	','	antropocentrismo	','	teocentrismo	','	humanismo	',	1	,'	216	');
INSERT INTO `resp` values(NULL, '	Guilherme I	','	Alexandre II	','	Felipe IV	','	Guilherme II	','	LuÃ­s XVI	',	3	,'	217	');
INSERT INTO `resp` values(NULL, '	manutenÃ§Ã£o do absolutismo monÃ¡rquico	','	fortalecimento da influÃªncia do clero sobre a sociedade	','	fim do regime absolutista e dos privilÃ©gios feudais	','	expansÃ£o dos privilÃ©gios feudais para a classe burguesa	','	adoÃ§Ã£o do protestantismo em toda a Europa	',	2	,'	218	');
INSERT INTO `resp` values(NULL, '	we	','	she	','	he	','	me	','	they	',	3	,'	219	');
INSERT INTO `resp` values(NULL, '	os carboidratos complexos.	','	as vitaminas lipossolÃºveis.	','	as vitaminas hidrossolÃºveis.	','	os carboidratos simples.	','	as proteÃ­nas	',	3	,'	220	');
INSERT INTO `resp` values(NULL, '	solidariedade mecÃ¢nica	','	solidariedade irracional	','	solidariedade material	','	solidariedade espiritual	','	solidariedade orgÃ¢nica	',	4	,'	221	');
INSERT INTO `resp` values(NULL, '	Richard Hartshorne	','	Vidal de la Blache	','	Yi-Fu Tuan	','	Milton Santos	','	Frederic Ratzel	',	2	,'	222	');
INSERT INTO `resp` values(NULL, '	careful	','	the most careful	','	the carefulest	','	the more careful	','	most careful	',	1	,'	223	');
INSERT INTO `resp` values(NULL, '	RevoluÃ§Ã£o Francesa	','	UnificaÃ§Ã£o da Alemanha	','	Guerra de SecessÃ£o dos Estados Unidos	','	Guerra Russo-Japonesa de 1905	','	Batalha de Waterloo	',	1	,'	224	');
INSERT INTO `resp` values(NULL, '	bigger	','	as big	','	as bigger than	','	more big	','	bigger than	',	4	,'	225	');
INSERT INTO `resp` values(NULL, '	1980	','	1989	','	1990	','	1991	','	2001	',	1	,'	226	');
INSERT INTO `resp` values(NULL, '	de danÃ§a.	','	escultÃ³rica.	','	caricatural.	','	teatral.	','	pictÃ³rica.	',	3	,'	227	');
INSERT INTO `resp` values(NULL, '	SÃ³crates	','	PlatÃ£o	','	AristÃ³teles	','	PitÃ¡goras	','	DemÃ³crito	',	1	,'	228	');
INSERT INTO `resp` values(NULL, '	Habsburgo	','	OrlÃ©ans	','	Valois	','	Romanov	','	Windsor	',	3	,'	229	');
INSERT INTO `resp` values(NULL, '	the most horrible	','	the horriblest	','	the more horrible	','	more horrible than	','	most horriblest	',	0	,'	230	');
INSERT INTO `resp` values(NULL, '	Alexis de Tocqueville.	','	Antonio Gramsci	','	John Stuart Mill	','	Robert Dahl	','	Gaetano Mosca	',	3	,'	231	');
INSERT INTO `resp` values(NULL, '	Socialismo utÃ³pico	','	Movimento iluminista	','	Catolicismo reformista	','	Movimento renascentista	','	Protestantismo	',	3	,'	232	');
INSERT INTO `resp` values(NULL, '	hipertensÃ£o e cegueira noturna.	','	diabetes e hipertensÃ£o.	','	cegueira noturna e desgastes nas articulaÃ§Ãµes.	','	cegueira noturna e hipertensÃ£o.	','	perda de peso acentuada e hipertensÃ£o.	',	1	,'	233	');
INSERT INTO `resp` values(NULL, '	Turn left	','	Turn right	','	On the corner	','	Go straight ahead	','	Go down	',	2	,'	234	');
INSERT INTO `resp` values(NULL, '	resfriado.	','	a MissÃ£o Francesa.	','	uma trupe de saltimbancos.	','	fugitivos da lei.	','	jesuÃ­tas.	',	1	,'	235	');
INSERT INTO `resp` values(NULL, '	escultura.	','	pintura.	','	construÃ§Ã£o.	','	peÃ§a teatral.	','	danÃ§a.	',	2	,'	236	');
INSERT INTO `resp` values(NULL, '	storesâ€™s window	','	windowâ€™s storeâ€™s	','	windows stores	','	window of the store	','	store of the window	',	3	,'	237	');
INSERT INTO `resp` values(NULL, '	la legumbre	','	el agua	','	la ave	','	la gran vitoria	','	el gran dÃ­a	',	2	,'	238	');
INSERT INTO `resp` values(NULL, '	SÃ£o Paulo	','	Belo Horizonte	','	Curitiba	','	Rio de Janeiro	','	Salvador	',	3	,'	239	');
INSERT INTO `resp` values(NULL, '	democracia representativa	','	democracia autoritÃ¡ria	','	democracia participativa	','	democracia direta	','	democracia indireta	',	0	,'	240	');
INSERT INTO `resp` values(NULL, '	stepson.	','	grandfather.	','	godfather.	','	brother-in-law.	','	sister-in-law.	',	3	,'	241	');
INSERT INTO `resp` values(NULL, '	eated	','	eaten	','	aten	','	ate	','	ated	',	3	,'	242	');
INSERT INTO `resp` values(NULL, '	RevoluÃ§Ã£o Francesa	','	RevoluÃ§Ã£o Inglesa	','	RevoluÃ§Ã£o Cubana	','	RevoluÃ§Ã£o Chinesa	','	Revolta da Chibata	',	0	,'	243	');
INSERT INTO `resp` values(NULL, '	Tese	','	AntÃ­tese	','	SÃ­ntese	','	Ironia	','	SensÃ­vel	',	0	,'	244	');
INSERT INTO `resp` values(NULL, '	Netuno.	','	Urano.	','	Terra.	','	Marte.	','	PlutÃ£o.	',	1	,'	245	');
INSERT INTO `resp` values(NULL, '	ao parto	','	Ã  morte	','	Ã  gestaÃ§Ã£o	','	Ã  infÃ¢ncia	','	ao bebe	',	0	,'	246	');
INSERT INTO `resp` values(NULL, '	Pintura.	','	Escultura.	','	Gravura.	','	MÃºsica.	','	Poesia.	',	2	,'	247	');
INSERT INTO `resp` values(NULL, '	Reforma Gregoriana	','	Renascimento	','	Ressurgimento CatÃ³lico	','	Contrarreforma	','	Renascimento CatÃ³lico	',	3	,'	248	');
INSERT INTO `resp` values(NULL, '	encontrar a substÃ¢ncia quÃ­mica Ãºnica	','	encontrar a substÃ¢ncia natural Ãºnica	','	encontrar as variadas substÃ¢ncias naturais	','	encontrar as variadas substÃ¢ncias quÃ­micas	','	encontrar a substÃ¢ncia inexistente	',	1	,'	249	');
INSERT INTO `resp` values(NULL, '	valorizar os deuses antigos	','	introduzir novos deuses	','	valorizar a juventude	','	introduzir novas idades Ã  noÃ§Ã£o de juventude	','	questionar os sofistas	',	1	,'	250	');
INSERT INTO `resp` values(NULL, '	monumento militar.	','	monumento astrolÃ³gico.	','	monumento estÃ©tico.	','	monumento cientÃ­fico.	','	monumento quÃ­mico.	',	1	,'	251	');
INSERT INTO `resp` values(NULL, '	Marie Curie	','	Malala Yousafzai	','	Margaret Heafield	','	NÃ­sia Floresta	','	Valentina Tereshkova	',	3	,'	252	');
INSERT INTO `resp` values(NULL, '	HeliocÃªntrica.	','	EmpÃ­rica.	','	EgocÃªntrica.	','	GeocÃªntrica.	','	MecanocÃªntrica.	',	0	,'	253	');
INSERT INTO `resp` values(NULL, '	Bride	','	Godmother	','	Wife	','	Uncle	','	Boyfriend	',	4	,'	254	');
INSERT INTO `resp` values(NULL, '	Francesco Redi	','	Lazzaro Spallanzani	','	Louis Pauster	','	Jan Baptist van Helmont	','	Thomas Henry Hurley	',	0	,'	255	');
INSERT INTO `resp` values(NULL, '	pudiera	','	podrÃ­a	','	pudieran	','	pudiere	','	pudieren	',	2	,'	256	');
INSERT INTO `resp` values(NULL, '	Escola dos Annales.	','	Escola FilosÃ³fica Positiva.	','	Escola MetÃ³dica.	','	Escola SocioeconÃ´mica.	','	Escola estruturalista.	',	2	,'	257	');
INSERT INTO `resp` values(NULL, '	RenÃ© Descartes	','	Francis Bacon	','	John Locke	','	David Hume	','	Friedrich Hegel	',	4	,'	258	');
INSERT INTO `resp` values(NULL, '	aceleraÃ§Ã£o da reforma agrÃ¡ria	','	reparaÃ§Ã£o de grupos excluÃ­dos	','	absorÃ§Ã£o dos trabalhadores urbanos	','	reconhecimento da diversidade Ã©tnica	','	enquadrÃ¡-los nas cotas	',	1	,'	259	');
INSERT INTO `resp` values(NULL, '	EducaÃ§Ã£o e sociologia	','	O capital	','	Manifesto comunista	','	O suicÃ­dio	','	Da divisÃ£o do trabalho social	',	4	,'	260	');
INSERT INTO `resp` values(NULL, '	desordem e progresso	','	ordem e retrocesso	','	ordem e progresso	','	retrocesso e progresso	','	desordem e retrocesso	',	2	,'	261	');
INSERT INTO `resp` values(NULL, '	positivista	','	dialÃ©tico	','	materialista	','	compreensivo	','	absolutista	',	0	,'	262	');
INSERT INTO `resp` values(NULL, '	in	','	on	','	at	','	by	','	for	',	0	,'	263	');
INSERT INTO `resp` values(NULL, '	Estudar sobre toda forma de organizaÃ§Ã£o humana, sem se limitar a um modelo especÃ­fico.	','	Catalogar todos os acontecimentos do passado.	','	Descobrir e organizar todas as formas de comunicaÃ§Ã£o jÃ¡ existentes.	','	Estudar os episÃ³dios do passado a partir de uma opiniÃ£o prÃ³pria.	','	Estabelecer uma Ãºnica e imutÃ¡vel verdade perante os fatos histÃ³ricos.	',	0	,'	264	');
INSERT INTO `resp` values(NULL, '	Era mais importante do que as divindades	','	Era considerado a prÃ³pria reencarnaÃ§Ã£o de HÃ³rus	','	NÃ£o tinha nenhuma relaÃ§Ã£o com o deus HÃ³rus	','	Era considerado a reencarnaÃ§Ã£o da deusa Ãsis	','	Era considerado a reencarnaÃ§Ã£o de OsÃ­ris, responsÃ¡vel pelo julgamento	',	1	,'	265	');
INSERT INTO `resp` values(NULL, '	organizaÃ§Ã£o sindical	','	participaÃ§Ã£o partidÃ¡ria	','	manifestaÃ§Ã£o religiosa	','	formaÃ§Ã£o profissional	','	afirmaÃ§Ã£o identitÃ¡ria	',	4	,'	266	');
INSERT INTO `resp` values(NULL, '	Monarquia Absolutista	','	Governo Socialista	','	Governo Republicano	','	Monarquia Liberal	','	Governos Fascistas	',	2	,'	267	');
INSERT INTO `resp` values(NULL, '	direitos polÃ­ticos	','	direitos civis	','	direitos difusos	','	direitos sociais	','	direitos culturais	',	3	,'	268	');
INSERT INTO `resp` values(NULL, '	Terra entre mares.	','	Terra seca	','	a)Â Â Â  Terra entre rios.	','	DÃ¡diva do Eufrates.	','	DÃ¡diva do Nilo	',	2	,'	269	');
INSERT INTO `resp` values(NULL, '	RevoluÃ§Ã£o Russa	','	RevoluÃ§Ã£o Chinesa	','	Absolutismo	','	Iluminismo	','	RevoluÃ§Ã£o Cubana	',	3	,'	270	');
INSERT INTO `resp` values(NULL, '	Revolta dos MalÃªs	','	Revolta da Vacina	','	Revolta da Chibata	','	Guerra de Canudos	','	Revolta dos Cabanos	',	3	,'	271	');
INSERT INTO `resp` values(NULL, '	genÃ³tipo	','	fenÃ³tipo	','	cromossomo	','	alelos	','	cariÃ³tipo	',	1	,'	272	');
INSERT INTO `resp` values(NULL, '	Heliocentrismo.	','	Empirismo.	','	Egocentrismo.	','	Geocentrismo.	','	Mecanitrismo.	',	3	,'	273	');
INSERT INTO `resp` values(NULL, '	Eufrates.	','	DanÃºbio.	','	Nilo.	','	Tigre.	','	Sena.	',	2	,'	274	');
INSERT INTO `resp` values(NULL, '	antes da escrita	','	contemporÃ¢neos Ã  escrita	','	depois da escrita	','	atravÃ©s da escrita	','	usando elementos da escrita	',	0	,'	275	');
INSERT INTO `resp` values(NULL, '	senso comum	','	religiÃ£o	','	filosofia	','	ciÃªncia	','	individualismo	',	2	,'	276	');
INSERT INTO `resp` values(NULL, '	epiderme.	','	periderme.	','	hipoderme.	','	endoderme.	','	derme.	',	2	,'	277	');
INSERT INTO `resp` values(NULL, '	o povo escocÃªs tentou restabelecer o catolicismo no paÃ­s.	','	os escoceses buscavam fortalecer a Igreja Anglicana no paÃ­s.	','	foi uma tentativa de restabelecer o presbiterianismo na EscÃ³cia.	','	foi uma tentativa de expulsar os catÃ³licos da Irlanda.	','	o conflito gerado nÃ£o teve relaÃ§Ãµes com a RevoluÃ§Ã£o.	',	2	,'	278	');
INSERT INTO `resp` values(NULL, '	regulaÃ§Ã£o.	','	conformaÃ§Ã£o.	','	metabolismo.	','	reguladores.	','	mantabolismo.	',	1	,'	279	');
INSERT INTO `resp` values(NULL, '	more tall than	','	taller than	','	the most tall	','	the tallest	','	tallest	',	3	,'	280	');
INSERT INTO `resp` values(NULL, '	JoÃ£o Calvino	','	AtanÃ¡sio de Alexandria	','	Martinho Lutero	','	JoÃ£o Huss	','	Papa JoÃ£o Paulo II	',	2	,'	281	');
INSERT INTO `resp` values(NULL, '	1945	','	1918	','	1942	','	1929	','	1914	',	1	,'	282	');
INSERT INTO `resp` values(NULL, '	Espanha	','	Brasil.	','	ColÃ´mbia.	','	FranÃ§a.	','	Inglaterra	',	0	,'	283	');
INSERT INTO `resp` values(NULL, '	Homo habilis	','	Homo erectus	','	Homo sapiens neanderthalensis	','	Homo sapiens sapiens	','	Australopithecus	',	3	,'	284	');
INSERT INTO `resp` values(NULL, '	hipoderme.	','	epiderme.	','	derme.	','	coriderme.	','	periderme.	',	1	,'	285	');
INSERT INTO `resp` values(NULL, '	Tales de Mileto e ParmÃªnides de ElÃ©ia	','	Tales de Mileto e PitÃ¡goras de Samos	','	PitÃ¡goras de Samos e ParmÃªnides de ElÃ©ia	','	ZenÃ£o de ElÃ©ia e PitÃ¡goras de Samos	','	ZenÃ£o de ElÃ©ia e Tales de Mileto	',	3	,'	286	');
INSERT INTO `resp` values(NULL, '	Him	','	Me	','	Her	','	You	','	Them	',	3	,'	287	');
INSERT INTO `resp` values(NULL, '	Jaime II, seu sobrinho	','	seu irmÃ£o, Jaime II	','	Guilherme de Orange	','	Henrique V	','	Margareth I	',	1	,'	288	');
INSERT INTO `resp` values(NULL, '	inclusive.	','	apesar.	','	portanto.	','	enquanto.	','	porÃ©m.	',	2	,'	289	');
INSERT INTO `resp` values(NULL, '	cold	','	colder than	','	the coldest	','	the cold	','	coldest	',	2	,'	290	');
INSERT INTO `resp` values(NULL, '	a classe	','	o filo	','	a famÃ­lia	','	o reino	','	a gÃªnero	',	0	,'	291	');
INSERT INTO `resp` values(NULL, '	NÃ­ger	','	Congo	','	Zambeze	','	Orange	','	Nilo	',	4	,'	292	');
INSERT INTO `resp` values(NULL, '	Ã‰ um agrossistema que visa, essencialmente, ao aumento da produtividade agrÃ­cola e Ã  reduÃ§Ã£o do tempo de produÃ§Ã£o.	','	Tipo de agricultura caracterizada pelo uso de tÃ©cnicas rudimentares ou tradicionais na produÃ§Ã£o.	','	Tipo de agricultura que se originou no sul e sudeste da Ãsia, onde hÃ¡ uma enorme produÃ§Ã£o de arroz em planÃ­cies inundÃ¡veis, com utilizaÃ§Ã£o intensiva de mÃ£o de obra.	','	Tipo de agricultura onde o cultivo da terra realizado por pequenos proprietÃ¡rios rurais, tendo, como mÃ£o de obra, essencialmente, o nÃºcleo familiar.	','	Sistemas sustentÃ¡veis de agricultura que nÃ£o permitem o uso de produtos quÃ­micos sintÃ©ticos prejudiciais para a saÃºde humana e para o meio ambiente, tais como alguns tipos variados de fertilizantes e agrotÃ³xicos sintÃ©ticos.	',	4	,'	293	');
INSERT INTO `resp` values(NULL, '	imaginaÃ§Ã£o	','	fabulaÃ§Ã£o	','	religiÃ£o	','	razÃ£o	','	ciÃªncia	',	3	,'	294	');
INSERT INTO `resp` values(NULL, '	Holanda	','	FranÃ§a	','	Inglaterra	','	Alemanha	','	Portugal	',	2	,'	295	');
INSERT INTO `resp` values(NULL, '	alimentos variados.	','	diferentes fontes de nutrientes.	','	preferÃªncia para o consumo de alimentos in natura.	','	ingestÃ£o suficiente de Ã¡gua.	','	exagero na quantidade de comida ingerida.	',	4	,'	296	');
INSERT INTO `resp` values(NULL, '	more long	','	longer than	','	more long than	','	more longer than	','	long	',	1	,'	297	');
INSERT INTO `resp` values(NULL, '	Era mais importante do que as divindades.	','	Era considerado a prÃ³pria reencarnaÃ§Ã£o de HÃ³rus.	','	NÃ£o tinha nenhuma relaÃ§Ã£o com o deus HÃ³rus.	','	Era considerado a reencarnaÃ§Ã£o da deusa Ãsis.	','	Era considerado a reencarnaÃ§Ã£o de OsÃ­ris, responsÃ¡vel pelo julgamento.	',	1	,'	298	');
INSERT INTO `resp` values(NULL, '	at	','	by	','	across	','	below	','	in front of	',	4	,'	299	');
INSERT INTO `resp` values(NULL, '	pepsina.	','	amilase.	','	lactase.	','	lipase.	','	maltase.	',	0	,'	300	');
INSERT INTO `resp` values(NULL, '	Rousseau	','	Voltaire	','	Karl Marx	','	Jean Bodin	','	Adam Smith	',	3	,'	301	');
INSERT INTO `resp` values(NULL, '	no pÃ¢ncreas.	','	no estÃ´mago.	','	no intestino grosso.	','	na vesÃ­cula biliar.	','	no esÃ´fago.	',	3	,'	302	');
INSERT INTO `resp` values(NULL, '	from	','	with	','	without	','	by	','	to	',	4	,'	303	');
INSERT INTO `resp` values(NULL, '	vermelha e amarela.	','	verde e vermelha.	','	azul e verde.	','	vermelha e azul.	','	marrom e vermelha.	',	0	,'	304	');
INSERT INTO `resp` values(NULL, '	permission.	','	ability.	','	request.	','	advice.	','	prohibition.	',	4	,'	305	');
INSERT INTO `resp` values(NULL, '	Netuno.	','	MercÃºrio.	','	Terra.	','	Marte.	','	PlutÃ£o.	',	1	,'	306	');
INSERT INTO `resp` values(NULL, '	o aumento e aceleraÃ§Ã£o da produÃ§Ã£o	','	distribuiÃ§Ã£o igualitÃ¡ria das riquezas produzidas	','	melhoramentos na qualidade da vida urbana	','	empobrecimento do governo britÃ¢nico	','	melhorias nas condiÃ§Ãµes de trabalho nas fÃ¡bricas	',	0	,'	307	');
INSERT INTO `resp` values(NULL, '	Comer	','	Comprar	','	Bailar	','	Estar	','	Vivir	',	4	,'	308	');
INSERT INTO `resp` values(NULL, '	despeja grades quantidades de alumÃ­nio no ambiente.	','	despeja esgoto sem tratamento no ambiente.	','	despeja organofosforados no ambiente.	','	despeja mercÃºrio no ambiente.	','	despeja restos de construÃ§Ãµes no ambiente.	',	1	,'	309	');
INSERT INTO `resp` values(NULL, '	Venceslau BrÃ¡s	','	Prudente de Morais	','	Artur Bernardes	','	Washington LuÃ­s	','	Deodoro da Fonseca	',	4	,'	310	');
INSERT INTO `resp` values(NULL, '	Direitos da primeira geraÃ§Ã£o, tais como os direitos civis	','	Direitos da segunda geraÃ§Ã£o, tais como direitos polÃ­ticos	','	Direitos da terceira geraÃ§Ã£o, como os direitos coletivos	','	Direitos da quarta geraÃ§Ã£o, como os direitos mundiais	','	Direitos da quinta geraÃ§Ã£o, como os direitos humanos	',	2	,'	311	');
INSERT INTO `resp` values(NULL, '	lactose.	','	maltose.	','	sacarose.	','	glicose.	','	celulose.	',	3	,'	312	');
INSERT INTO `resp` values(NULL, '	Verbo	','	Adjetivo	','	Sustantivo	','	Adverbio	','	Pronombre	',	3	,'	313	');
INSERT INTO `resp` values(NULL, '	Gestos.	','	Sinais.	','	InformaÃ§Ãµes.	','	Dinheiro.	','	Coisas.	',	2	,'	314	');
INSERT INTO `resp` values(NULL, '	Escultor.	','	Jornalista.	','	Fazendeiro.	','	Pintor.	','	Grafiteiro.	',	4	,'	315	');
INSERT INTO `resp` values(NULL, '	genoma	','	cariÃ³tipo	','	genÃ³tipo	','	fenÃ³tipo	','	cromatina	',	0	,'	316	');
INSERT INTO `resp` values(NULL, '	inquilinismo, parasitismo, competiÃ§Ã£o e predaÃ§Ã£o.	','	mutualismo, amensalismo, parasitismo e predaÃ§Ã£o.	','	amensalismo, parasitismo, competiÃ§Ã£o e predaÃ§Ã£o.	','	comensalismo, inquilinismo, competiÃ§Ã£o e predaÃ§Ã£o.	','	amensalismo, parasitismo, competiÃ§Ã£o e sociedade.	',	2	,'	317	');
INSERT INTO `resp` values(NULL, '	mitologia	','	amizade	','	irracionalidade	','	rigor	','	experimentaÃ§Ã£o	',	3	,'	318	');
INSERT INTO `resp` values(NULL, '	Thomas Hobbes	','	John Locke	','	Montesquieu	','	Jean-Jacques Rousseau	','	John Stuart Mill	',	3	,'	319	');
INSERT INTO `resp` values(NULL, '	moderna	','	pÃ³s-moderna	','	feudal	','	asiÃ¡tica	','	comunista	',	0	,'	320	');
INSERT INTO `resp` values(NULL, '	Who	','	Whose	','	Whom	','	Where	','	When	',	1	,'	321	');
INSERT INTO `resp` values(NULL, '	aminoÃ¡cidos.	','	Ã¡cidos graxos.	','	ceras.	','	esteroides.	','	peptÃ­deos.	',	3	,'	322	');
INSERT INTO `resp` values(NULL, '	epiderme.	','	periderme.	','	mucosa.	','	adiposa.	','	glia.	',	2	,'	323	');
INSERT INTO `resp` values(NULL, '	o eclipse total da Lua.	','	o eclipse total do Sol.	','	o eclipse parcial do Sol.	','	o eclipse parcial da Lua.	','	o eclipse parcial da Terra.	',	2	,'	324	');
INSERT INTO `resp` values(NULL, '	Seus olhos sÃ£o como o fogo.	','	Ãgua mole pedra dura tanto bate atÃ© que fura.	','	Perco a piada, mas nÃ£o perco a ferroada.	','	Amigos, amigos, negÃ³cios Ã  parte.	','	Quem nÃ£o Ã© visto, nÃ£o Ã© lembrado.	',	2	,'	325	');
INSERT INTO `resp` values(NULL, '	o epÃ­teto	','	o filo	','	a famÃ­lia	','	o reino	','	o gÃªnero	',	1	,'	326	');
INSERT INTO `resp` values(NULL, '	Along	','	Across from	','	Around	','	Far	','	Near	',	2	,'	327	');
INSERT INTO `resp` values(NULL, '	positiva	','	imparcial	','	negativa	','	saudÃ¡vel	','	indeterminada	',	2	,'	328	');
INSERT INTO `resp` values(NULL, '	o parlamentarismo	','	o presidencialismo	','	o semi-presidencialismo	','	a aristocracia	','	a monarquia absolutista	',	4	,'	329	');
INSERT INTO `resp` values(NULL, '	Membros da nobreza italiana.	','	Mecenas dos artistas.	','	Dramaturgos famosos.	','	Personagens da commedia dellâ€™arte.	','	Integrantes de uma trupe.	',	3	,'	330	');
INSERT INTO `resp` values(NULL, '	Modo de produÃ§Ã£o	','	Socialismo	','	Fato social	','	AÃ§Ã£o Social	','	Ideologia	',	0	,'	331	');
INSERT INTO `resp` values(NULL, '	cÃ¡lcio.	','	enxofre.	','	iodo.	','	fÃ³sforo.	','	flÃºor.	',	2	,'	332	');
INSERT INTO `resp` values(NULL, '	as bad than	','	bad than	','	badder than	','	the worse	','	as bad as	',	4	,'	333	');
INSERT INTO `resp` values(NULL, '	as low as	','	lower as	','	not as lower as	','	as lower as	','	lower so	',	0	,'	334	');
INSERT INTO `resp` values(NULL, '	aparecieron	','	haz	','	ponga	','	podrÃ­a	','	han sido	',	0	,'	335	');
INSERT INTO `resp` values(NULL, '	Max Weber	','	Ã‰mile Durkheim	','	Friedrich Engels	','	Friedrich Hegel	','	Friedrich Nietzsche	',	2	,'	336	');
INSERT INTO `resp` values(NULL, '	my	','	ours	','	hers	','	mine	','	theirs	',	0	,'	337	');
INSERT INTO `resp` values(NULL, '	pronombre relativo	','	adverbio	','	sustantivo	','	verbo	','	adjetivo	',	2	,'	338	');
INSERT INTO `resp` values(NULL, '	vitÃ³ria e enriquecimento da Alemanha	','	derrota e esfacelamento da economia alemÃ£	','	derrota da Inglaterra e empobrecimento de sua sociedade	','	surgimento do fascismo na FranÃ§a	','	ocorrÃªncia da RevoluÃ§Ã£o Bolchevique na Turquia	',	1	,'	339	');
INSERT INTO `resp` values(NULL, '	DivisÃ£o do trabalho	','	DivisÃ£o entre sexos	','	DivisÃ£o entre geraÃ§Ãµes	','	DivisÃ£o entre guerreiros	','	DivisÃ£o religiosa	',	0	,'	340	');
INSERT INTO `resp` values(NULL, '	Elizabeth I	','	Jaime I	','	Carlos II	','	Carlos I	','	Henrique VIII	',	2	,'	341	');
INSERT INTO `resp` values(NULL, '	A guerra ocorreu predominantemente em territÃ³rio asiÃ¡tico.	','	Os EUA participaram em apoio aos paÃ­ses da TrÃ­plice Entente.	','	A Alemanha entrou na guerra em apoio Ã  Ãustria-Hungria.	','	A ItÃ¡lia mudou de lado no decorrer da guerra.	','	Portugal e Espanha se mantiveram neutros.	',	0	,'	342	');
INSERT INTO `resp` values(NULL, '	Com eucalipto.	','	Com carvalho.	','	Com papiro.	','	Com ipÃª.	','	Com reciclagem.	',	2	,'	343	');
INSERT INTO `resp` values(NULL, '	alcanzar	','	cansancio	','	estudiantes	','	puentes	','	orÃ­genes	',	2	,'	344	');
INSERT INTO `resp` values(NULL, '	InstituiÃ§Ãµes.	','	Ordens.	','	Decretos.	','	Leis.	','	Mandamentos.	',	0	,'	345	');
INSERT INTO `resp` values(NULL, '	on	','	at	','	from	','	to	','	in	',	4	,'	346	');
INSERT INTO `resp` values(NULL, '	Between	','	Near	','	Under	','	In	','	On	',	2	,'	347	');
INSERT INTO `resp` values(NULL, '	I	','	He	','	She	','	They	','	You	',	3	,'	348	');
INSERT INTO `resp` values(NULL, '	depois	','	jÃ¡	','	enquanto	','	antes	','	ainda	',	2	,'	349	');
INSERT INTO `resp` values(NULL, '	Idealista	','	Materialista	','	Existencialista	','	Racionalista	','	Empirista	',	1	,'	350	');
INSERT INTO `resp` values(NULL, '	epiderme.	','	mesoderme.	','	periderme.	','	ectoderme.	','	endoderme.	',	4	,'	351	');
INSERT INTO `resp` values(NULL, '	Socialismo cientÃ­fico	','	Idealismo hegeliano	','	Materialismo dialÃ©tico	','	Existencialismo	','	Comunismo	',	1	,'	352	');
INSERT INTO `resp` values(NULL, '	at	','	in	','	on	','	until	','	under	',	0	,'	353	');
INSERT INTO `resp` values(NULL, '	James Cameron.	','	Steven Spielberg.	','	Quentin Tarantino.	','	Lucien Freud.	','	Fernando Meireles.	',	0	,'	354	');
INSERT INTO `resp` values(NULL, '	movimento republicano	','	movimento socialista	','	movimento trabalhista	','	movimento feminista	','	movimento sindical	',	0	,'	355	');
INSERT INTO `resp` values(NULL, '	expensiver than	','	more expensive than	','	the expensivest	','	the most expensive	','	expensive	',	3	,'	356	');
INSERT INTO `resp` values(NULL, '	Grandmaâ€™s cookieâ€™s	','	Grandmasâ€™ cookiesâ€™	','	Grandmaâ€™s cookie	','	Grandmaâ€™s cookies	','	Grandma cookiesâ€™	',	3	,'	357	');
INSERT INTO `resp` values(NULL, '	talked.	','	walked.	','	studied.	','	started.	','	visited.	',	2	,'	358	');
INSERT INTO `resp` values(NULL, '	porque	','	contudo	','	ao invÃ©s de	','	portanto	','	porÃ©m	',	2	,'	359	');
INSERT INTO `resp` values(NULL, '	O Sol estÃ¡ parado em relaÃ§Ã£o Ã  Terra.	','	Ã‰ possÃ­vel que um mÃ³vel esteja em movimento em relaÃ§Ã£o a um referencial e em repouso em relaÃ§Ã£o a outro.	','	Se um mÃ³vel estÃ¡ em movimento em relaÃ§Ã£o ao solo, o solo estarÃ¡ em movimento em relaÃ§Ã£o ao mÃ³vel.	','	Se um corpo A estÃ¡ em repouso em relaÃ§Ã£o a outro corpo B, entÃ£o o corpo B estarÃ¡ tambÃ©m em repouso em relaÃ§Ã£o ao corpo A.	','	Ã‰ possÃ­vel um corpo A estar em movimento em relaÃ§Ã£o a dois outros corpos B e C, e B estar em repouso em relaÃ§Ã£o a C.	',	0	,'	360	');
INSERT INTO `resp` values(NULL, '	less optimistic than	','	less optimistic	','	as optimistic than	','	less optimistic so	','	not so optimistic	',	0	,'	361	');
INSERT INTO `resp` values(NULL, '	apoiar Martinho Lutero e os outros reformadores	','	organizar uma cruzada contra os muÃ§ulmanos	','	resgatar os judeus Ã  fÃ© catÃ³lica	','	conter o avanÃ§o do budismo	','	combater o avanÃ§o da Reforma Protestante	',	4	,'	362	');
INSERT INTO `resp` values(NULL, '	carbÃ´nico	','	nitrogÃªnio	','	metano	','	hÃ©lio	','	oxigÃªnio	',	4	,'	363	');
